README.md
- Suggests a folder structure
- Adds some generic files such as `.gitignore` and `pull_request_template.md`
We need to create some initial structure so that Karina can start populating the Next.js generic config!
=> Create initial folder structure

app/.eslintrc.json, app/.prettierrc.json, app/README.md, app/__mocks__/styleMock.js, app/jest.config.js, app/next.config.js, app/package.json, app/pages/_app.tsx, app/pages/api/hello.ts, app/pages/index.tsx, app/test/jest.setup.js, app/test/pages/index.test.tsx, app/yarn.lock
[WMDP-100](https://wicmtdp.atlassian.net/browse/WMDP-100)
- add jest plugin 
- remove recommended prettier plugin in favor for prettier plugin
- addresses eslint errors 
- suppresses import React linting error and documents change in README 
> locally run `yarn lint`
=> fix eslint errors

README.md, app/Dockerfile, docker-compose.yml
- https://wicmtdp.atlassian.net/browse/WMDP-98
- Added a `Dockerfile` to dockerize the Next.js application
- Added a `docker-compose.yml` to facilitate running the Docker image
This PR dockerizes the application for deployment to AWS, as well as for improved local development.
> Screenshots, GIF demos, code examples or output to help show the changes working as expected. ProTip: you can drag and drop or paste images into this textbox.
Follow the new instructions in the `README.md` to test that all is working as outlined.
=> Dockerize the application

app/.prettierignore, app/jest.config.js, app/tsconfig.json
- N/A
- Updates `.prettierignore` to allow prettier to format project files
Follow up to #16. I reviewed the files that prettier was formatting and I think they shouldn't be ignored.
> Screenshots, GIF demos, code examples or output to help show the changes working as expected. ProTip: you can drag and drop or paste images into this textbox.
`yarn format`
=> Let prettier format project files.

app/styles/_uswds-theme-custom-styles.scss
- N/A
- Add styles that got left out of PR #26 
When we created a new PR for #26, some styles got left behind. This PR brings them in.
> Screenshots, GIF demos, code examples or output to help show the changes working as expected. ProTip: you can drag and drop or paste images into this textbox.
Should now look like this:
=> Add layout styles missing from PR #26.

infra/README.md, infra/bootstrap/account/main.tf, infra/bootstrap/account/outputs.tf, infra/modules/bootstrap/main.tf
Resolves #90 
Resolves #97 
* Include lock table name in KMS key description
* Use AWS_PROFILE env var for AWS authentication
* Namespace terraform backend resources to project
* Output backend resource names explicitly
* Add infrastructure cleanup instructions
Added some tweaks to namespace resources under the project name to avoid name conflicts, which will help on projects and also help for platform testing.
* Ran through all the instructions, including cleanup instructions
=> Tweaks to infra bootstrap

.github/workflows/ci-infra.yml, .github/workflows/template-only-ci-app.yml, Makefile, infra/bootstrap/account/main.tf, infra/envs/dev/main.tf, infra/envs/prod/main.tf, infra/envs/staging/main.tf, infra/modules/bootstrap/main.tf, infra/modules/common/outputs.tf
Resolves #119
- Add ci-infra.yml
- Add make infra-lint
- Add make infra-format
Add tf linting. Will add checkov in a future PR
CI infra should run on this PR
=> Add infra lint check

docs/decisions/0001-ci-cd-interface.md, docs/decisions/0002-use-custom-implementation-of-github-oidc.md
n/a
- Add ADR for OIDC implementation
see [slack thread](https://nava.slack.com/archives/C205Q1RA8/p1664982497619069?thread_ts=1664913762.000269&cid=C205Q1RA8)
n/a
=> Add ADR for OIDC implementation

docs/decisions/0003-manage-ecr-in-prod-account-module.md
n/a
- Add ADR for how to manage ECR repositories
See [Slack thread](https://nava.slack.com/archives/C03G1SWD9H7/p1665156774781419)
n/a
=> Add ADR for how to manage ECR repositories

.github/workflows/ci-infra.yml, Makefile, docs/compliance.md
Resolves #102 
- Add tfsec check
In #102 we talked about having both checkov and tfsec for full coverage, so this PR adds tfsec. We added checkov in #132 
* CI
* Ran make `infra-check-compliance` locally
=> Add tfsec check

docs/infra/set-up-aws-account.md, infra/accounts/account/main.tf, template-only-bin/set-up-account.sh
n/a
* Use project_config.default_region for account region rather than hardcoded value
* Use actual account region rather than hardcoded value
I'm going through the platform instructions and noticing some tiny tweaks to make.
CI
=> Use project default region for account region

docs/infra/set-up-aws-account.md, docs/infra/set-up-infrastructure-tools.md
Resolves #87 
* Add instruction to check AWS auth
* Fix broken doc link
Just a couple of tiny documentation tweaks
N/A
=> Add simple instruction to verify AWS auth

README.md, template-only-bin/install-template.sh
n/a
see title
Add script for installing the template (basically copy pasting the instructions from the README). This isn't strictly needed, but will help with some automation for the platform development.
I ran the script, and it seems to work properly
=> Add script for installing the template

template-only-bin/update-template.sh
n/a
see title
I made a syntax error #235 that [broke template deploys](https://github.com/navapbc/template-infra/actions/runs/4347050687). This PR fixes that
i think the easiest way to test this is to just "do it live"
=> Fix syntax error in update script

infra/modules/terraform-backend-s3/main.tf
Resolves #251 
see title
see ticket description
CI
=> Remove server logging on tf_log bucket

infra/test/infra_test.go
n/a
* Remove extra call to terraform init that doesn't pass backend-config
* Update terraform init call in build-repository to pass backend-config
Didn't realize that infra e2e tests were broken since they were commented out. See this broken e2e run in platform-test: https://github.com/navapbc/platform-test/actions/runs/5016218308/jobs/8992804567
This change fixes the e2e tests. It passes in backend-config to the terraform init calls.
Tested on platform-test in this PR https://github.com/navapbc/platform-test/pull/12
=> Fix project CI-infra e2e job

.github/workflows/cd.yml, .github/workflows/database-migrations.yml, Makefile, app/Dockerfile, app/db-migrate, app/migrations.sql, bin/run-command.sh, bin/run-database-migrations.sh, infra/app/service/outputs.tf, infra/modules/service/outputs.tf, template-only-bin/update-template.sh, template-only-docs/application-requirements.md
Resolves https://github.com/navapbc/template-infra/issues/127
* Add cluster name and service name to service layer outputs
* Add run-command script for running custom commands in the application container
* Add run-database-migrations script for updating the task definition and running the "db-migrate" container command
* Update example app with a db-migrate command that runs a migrations.sql SQL script
* Add database-migrations workflow for calling run-database-migrations script after building and publishing
* Update cd workflow to call database-migrations workflow
* Update application-requirements.md
* Update update-template.sh to ignore changes to database-migrations.yml
These changes implement database migrations infrastructure for applications. Assuming the application has a …
=> Add database migrations

app/db-migrate, app/migrations.sql
n/a
see title
feedback from @KevinJBoyer: https://github.com/navapbc/template-infra/pull/316#discussion_r1237140037
n/a/ just adding comments
=> Add comments explaining example app migrations

infra/app/service/main.tf, infra/modules/monitoring/main.tf, infra/modules/monitoring/outputs.tf, infra/modules/monitoring/variables.tf, infra/modules/service/outputs.tf
https://github.com/navapbc/template-infra/issues/328
Added monitoring module with list of most common alerts and sns topic for notifications.
Added module call from /app/service/ with default alert thresholds values
Every alert could be enabled/disabled by setting/unsetting alert threshold.
Based on the monitoring project requirements, I incorporated a monitoring module into our existing Terraform code. The goal is to enhance our infrastructure by adding basic ECS metrics alerts with configurable thresholds. 
- Run command to deploy app and monitoring. 
`TF_CLI_ARGS_apply="-var=image_tag=8a1ebfde68391049d022f6c959557cafb179869e" make infra-update-app-service APP_NAME=app ENVIRONMENT=staging`
Ensure all alerts have been created via AWS UI - passed
- Set alert threshold value that will …
=> feat: add alerts and sns topic

infra/app/service/main.tf, infra/modules/monitoring/main.tf, infra/modules/monitoring/variables.tf
https://github.com/navapbc/template-infra/issues/328
This PR is to address final comments from https://github.com/navapbc/template-infra/pull/336
Removed configurable thresholds for alerts and some of the resources are renamed
Changes applied to test account
automated tests
=> feat: remove threshold configuration, resource names

.github/pull_request_template.md
n/a
see title
Clarify the testing section with broader instructions that apply to backend PRs.
N/A
=> Clarify PR template instructions

.github/workflows/ci-infra.yml, .github/workflows/database-migrations.yml, bin/run-database-migrations.sh
#325 
* added `::group::` to the database migration output
* add `--quiet` to checkov checks (this only displays failed checks)
Successful run: https://github.com/navapbc/platform-test/actions/runs/5646581264/job/15294833613
=> Group verbose logs

CONTRIBUTING.md, template-only-docs/template-development-workflow.md
n/a
see title
Based on feedback from @aplybeah and @charles-nava the template development workflow is confusing so I thought I'd document it.
n/a
=> Add template development workflow

README.md, docs/infra/README.md, docs/infra/destroy-infrastructure.md, docs/infra/set-up-app-env.md, infra/project-config/main.tf, template-only-docs/set-up-ci.md
Various documentation updates based on my experience setting up the infra template on another project.
=> Update instructions based on an initial project test run

.gitignore
Resolves #222 
see title
Pushing this off too long. Decided to do this based on recent feedback. Also decided an inline comment is probably better and simpler than a full ADR.
n/a
=> Ignore terraform lock files

infra/modules/database/role_manager/role_manager.py
Pulling over @KevinJBoyer's changes, which fixed an issue we were seeing:
```
code: SqlState(E42501), message: "permission denied for table application"
```  
- `GRANT USAGE ON` doesn't seem to necessarily provide access to tables underneath: https://stackoverflow.com/questions/17338621/what-does-grant-usage-on-schema-do-exactly
- So, either that needs to be the first migration (like it’s done on pfml), or it needs to be done in the role manager.
Deployed on our project and observed the error no longer happening.
=> Fix table privileges

infra/app/app-config/main.tf
n/a
* Add instruction to update account name in app config
* Clarify account_names_by_environment comment
This comment caused some confusion so hoping to remove ambiguity
n/a
=> Add instruction to update account name in app config

template-only-docs/set-up-ci.md
Resolves #389 
Remove blob on setting role arn
PR #319 already made this setting automatic
=> [ISSUE 389] Update set-up-ci.md

infra/app/app-config/env-config/outputs.tf, infra/app/database/main.tf, infra/app/service/main.tf, infra/modules/database/authentication.tf, infra/modules/database/variables.tf, infra/modules/service/access-control.tf, infra/modules/service/outputs.tf, infra/modules/service/variables.tf
Part of [354](https://github.com/navapbc/template-infra/issues/354)
Added resources for eventual separation of migrator and app roles
- Input vars
- IAM Policies
- Used as part 1 of multipart installation of split roles
- TF validated in [platform-test](https://github.com/navapbc/platform-test/pull/35)
=> Add non-functional app and migrator policies and roles

infra/networks/main.tf
n/a fix bug introduced in #406 
see title
Fix terraform variable access bug:
dev/testing in https://github.com/navapbc/platform-test/pull/37
=> Fix terraform infra variable access

README.md
n/a
n/a
Add instructions for how to pull in updates to the template
=> Add update template instructions

Makefile
n/a
* Update Makefile .PHONY list
* Remove unused make infra-validate-env-template target
* Add Makefile help comment on check compliance targets and validate target
Was just looking in the Makefile and realized there's some leftover cruft.
The .PHONY list in the Makefile was out of date and included some targets that no longer exist.
Also remove `make infra-validate-env-template` which was leftover from before we moved all backend configs to be file-based.
CI should cover this change.
=> Update Makefile .PHONY list

.github/workflows/ci-infra.yml, .github/workflows/ci-vulnerability-scans.yml, Makefile, docs/infra/set-up-infrastructure-tools.md
Resolves https://github.com/navapbc/template-application-flask/issues/25
see title
* Adding a linter for GitHub actions to catch simple errors
Action linter should run in CI on this PR (and in future PRs once this PR is merged)
=> Add GitHub action linter

infra/app/service/main.tf, infra/modules/service/access-control.tf
n/a
see title
In #407 we created new db policies, and in #411 we intended to have the app service use those new policies, but we forgot to update the policy arns that we passed in to the service module. This change fixes that.
developed and tested on platform-test in https://github.com/navapbc/platform-test/pull/45
=> Pass correct roles to service module

bin/run-command.sh, bin/run-database-migrations.sh, infra/app/service/main.tf, infra/modules/database/authentication.tf, infra/modules/service/database-access.tf, infra/modules/service/variables.tf
Related to issue #354 
- Update run-command and run-database-migrations to include role override
- Remove references to deprecated policy
- Remove deprecated policy
> Testing carried out in [platform-test](https://github.com/navapbc/platform-test/pull/55)
=> Remove deprecated policy and references

docs/decisions/index.md, docs/decisions/infra/0005-separate-database-infrastructure-into-separate-layer.md, docs/decisions/infra/0007-database-migration-architecture.md, docs/decisions/infra/0008-consolidate-infra-config-from-tfvars-files-into-config-module.md, docs/decisions/infra/0009-separate-app-infrastructure-into-layers.md, docs/infra/module-architecture.md, docs/infra/module-dependencies.md
Resolves #431 
see title
see ticket, this came out of a discussion on a previous PR
n/a, just docs
=> Add ADR documenting rationale for separating app infra layers

infra/modules/service/main.tf
N/A
- Remove redundant comment
Noticed a redundant comment. This PR removes it.
No impact. Removes a comment.
=> Remove redundant comment

infra/modules/database/main.tf, infra/modules/database/role-manager.tf, infra/modules/database/role_manager/role_manager.py
Resolves #286 
- Adjust get_password to decode associated json
- Update param name
Update for security
Tested in [platform-test](https://github.com/navapbc/platform-test/pull/61)
=> Use secret manager for db master password

docs/decisions/infra/0010-feature-flags-system-design.md
n/a
see title
created a tech spec for how to design the feature flags system
n/a
=> Feature flags system design ADR

infra/modules/database/main.tf
Resolves #491
see title
see ticket
Developed and tested on https://github.com/navapbc/platform-test/pull/70
=> Pin db cluster engine version

app/app.py, infra/modules/service/main.tf
Resolves https://github.com/navapbc/template-infra/issues/553
see title
When working on another project we realized it would be useful for the application to have access to the current version of the application.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/89
=> Add IMAGE_TAG environment variable

infra/modules/storage/access-control.tf
Resolves https://github.com/navapbc/template-infra/issues/558
See title
See ticket
Developed and tested in https://github.com/navapbc/platform-test/pull/93
=> Add ListBucket permission for storage bucket

infra/README.md, template-only-docs/application-requirements.md
N/A
- Update documentation
I received feedback from a user that shared that these particular setup instructions were confusing. I've modified them to hopefully be clearer.
N/A
=> Clarify setup documentation

.github/workflows/ci-app-vulnerability-scans.yml
N/A
- Update `/.github/workflows/ci-app-vulnerability-scans.yml` so that changes to that file trigger the workflow
When the file was renamed in #465, the triggers for the workflow weren't updated to reflect the name change.
We can see the checks are now triggered by comparing …
=> Fix omitted filename change when renaming ci-app-vulnerability-scans.yml

.github/workflows/ci-infra-service.yml, .github/workflows/ci-infra.yml, .github/workflows/template-only-ci-infra.yml, infra/accounts/main.tf, infra/app/build-repository/main.tf, infra/app/database/main.tf, infra/app/service/main.tf, infra/networks/main.tf
Resolves #587
- Pins CI/CD to terraform 1.8.3
- Pessimistically pins terraform required version to `~> 1.8.0`
We are currently pinning our terraform version only to the major version:
```
required_version = ">= 1.2.0, < 2.0.0"
```
This causes mysterious and sometimes hard to debug issues like #586. We should instead pin to the terraform minor version (e.g. 1.8.x) and do controlled upgrades to new minor versions (e.g. 1.8.x -> 1.9.x).
This PR uses the [pessimistic constraint](https://developer.hashicorp.com/terraform/language/expressions/version-constraints) operator to ensure that only updates …
=> Pin terraform version

.github/workflows/build-and-publish.yml
Resolves https://github.com/navapbc/template-infra/issues/606
see title
See context in ticket
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/99
=> Fix build/publish concurrency group

docs/infra/style-guide.md, infra/README.md
I am realizing that it would be nice to point to style guide when providing nit style comments on PRs to engineers.
Note that we have some tech debt that doesn't adhere to the style guides we recommend but I think that's ok for now.
=> Add infra style guide

template-only-bin/install-template.sh
Resolves #{TICKET NUMBER OR URL}
- Add .gitignore to template install
The root .gitignore wasn't being copied over when the install scripts were run.
=> Update install-template.sh to include .gitignore

bin/account-ids-by-name.sh, bin/check-database-roles.sh, bin/check-github-actions-auth.sh, bin/configure-monitoring-secret.sh, bin/create-or-update-database-roles.sh, bin/create-tfbackend.sh, bin/current-account-config-name.sh, bin/deploy-release.sh, bin/is-image-published.sh, bin/lint-markdown.sh, bin/publish-release.sh, bin/run-command.sh, bin/run-database-migrations.sh, bin/set-up-current-account.sh, bin/terraform-apply.sh, bin/terraform-init-and-apply.sh, bin/terraform-init.sh
Resolves #532 
- All local variables are now lowercase. I only identified a single, actual environment variable `IFS` in all the scripts. Please double check I'm correct!
- I made some trailing whitespace and extra newline adjustments.
=> Rename internal shell variables to be lower case

bin/deploy-release.sh
Fixes #532 
See [Rename internal shell variables to be lower case](https://github.com/navapbc/template-infra/pull/629)
- Revert lowercase `TF_CLI_ARGS_apply` & environment variables from the perspective of the make file
[Deploy to platform-test looks good](https://github.com/navapbc/platform-test/actions/runs/9470097199)
[Test branch](https://github.com/navapbc/platform-test/tree/daphnegold/fix-532-test)
=> Fix lowercase bug introduced to deploy-release.sh

docs/decisions/index.md, docs/decisions/infra/0009-separate-app-infrastructure-into-layers.md
n/a
- Update ADR + fix minor typo
=> Update decision log index

docs/infra/service-command-execution.md
N/A
We hit a self-imposed issue on the FFS project. To prevent others from
spending as much time, I've added our troubleshooting instructions to
the documentation here since ECS Exec is somewhat of a finnicky system
to get operating correctly.
N/A
N/A
=> Add troubleshooting instructions to ECS Exec documentation

docs/infra/develop-and-test-infrastructure-in-isolation-using-workspaces.md
Addressing post merge comments from https://github.com/navapbc/template-infra/pull/656
=> Update docs to address post-merge comments from PR #656

.github/workflows/ci-app-pr-environment-destroy.yml, .github/workflows/ci-app-pr-environment-update.yml, .github/workflows/pr-environment-destroy.yml, .github/workflows/pr-environment-update.yml, bin/update-pr-environment, docs/infra/pull-request-environments.md
n/a
see title
The PR environment update comments were too noisy, so this change moves the PR environment information to the PR description.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/118
=> Move PR environment info to PR description

infra/app/app-config/env-config/variables.tf, infra/modules/auth-github-actions/variables.tf, infra/modules/container-image-repository/variables.tf, infra/modules/database/variables.tf, infra/modules/domain/variables.tf, infra/modules/feature-flags/variables.tf, infra/modules/monitoring/variables.tf, infra/modules/network/variables.tf, infra/modules/service/variables.tf, infra/modules/storage/variables.tf
Resolves #618 
- Alphabetize `variables.tf` files :D 
[platform-test PR](https://github.com/navapbc/platform-test/pull/121)
=> Alphabetize variables.tf files

infra/accounts/outputs.tf, infra/app/app-config/env-config/outputs.tf, infra/app/app-config/outputs.tf, infra/app/service/outputs.tf, infra/modules/domain/outputs.tf, infra/modules/feature-flags/outputs.tf, infra/modules/service/outputs.tf, infra/modules/terraform-backend-s3/outputs.tf, infra/networks/outputs.tf, infra/project-config/outputs.tf
Resolves #604
> Alphabetize all the output things
[platform-test PR](https://github.com/navapbc/platform-test/pull/124) < see passing terratest & deploy
=> Organize outputs alphabetically

bin/run-database-migrations
Resolves https://github.com/navapbc/template-infra/issues/675
see title
Credit to @tdooner for the fix
see ticket: https://github.com/navapbc/template-infra/issues/675
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/127
=> Update task_executor IAM policy before running migrations

e2e/app/playwright.config.js
The typo made the merge not work
=> Playwright baseURL var should be URL

.github/workflows/e2e-tests.yml, .github/workflows/pr-environment-checks.yml, Makefile, docs/e2e/e2e-checks.md, e2e/Dockerfile, e2e/package-lock.json, e2e/package.json
https://github.com/navapbc/template-infra/issues/735
- dockerize e2e tests with playwright
Tested on `platform-test-nextjs` => https://github.com/navapbc/platform-test-nextjs/pull/88
=> E2E Dockerize

Makefile, e2e/package-lock.json
Resolves https://github.com/navapbc/template-infra/issues/720
- Makefile and package-lock patch
- Some of the diff stats were conflicting based on what was merged in this repo https://github.com/navapbc/template-infra/pull/776/files - versus all the changes we had in the `platform-test-nextjs` repo https://github.com/navapbc/platform-test-nextjs/pull/89/files
=> Run E2E sharding part 1 patch

e2e/Dockerfile, e2e/package-lock.json, e2e/package.json
Resolves #801 
- Update npm packages
- bump Dockerfile playwright image version
`platform-test-nextjs` PR:
This PR:
Tested on `platform-test-nextjs` => https://github.com/navapbc/platform-test-nextjs/pull/94
=> Update e2e packages

app/Dockerfile, app/Makefile, template-only-bin/update-docker-digest
Fix example app build.
See CI.
=> app: Install available postgresql-client and pin docker digest

.github/workflows/send-system-notification.yml, infra/project-config/outputs.tf, infra/project-config/system-notifications.tf
Related to (but doesn't resolve) https://github.com/navapbc/template-infra/issues/808
- Add callable workflow send-system-notification.yml
- Add project-config/system-notifications.tf configuration for defining channel
I plan on adding documentation in a future PR once I get this working end to end for a few workflows
developed and tested on platform-test in https://github.com/navapbc/platform-test/pull/144
=> Add send-system-notification callable workflow

Makefile
Resolves #814 
- Add informational to use make command to show reports when done running e2e tests
=> E2E informational to run make command to show report

.github/workflows/scan-orphaned-pr-environments.yml, template-only-docs/release-management.md
n/a
see title
a guide for platform maintainers
n/a
=> Add template release management documentation

template-only-docs/template-technical-design-principles.md
n/a
see title
Discussed some of these 1:1 with @doshitan 
n/a
=> Add template technical design principles

infra/modules/notifications-email-domain/resources/dns.tf, infra/modules/notifications-email-domain/resources/main.tf
- Fixes the DNS record for the MAIL FROM domain
- Adds the DNS record for the DMARC domain
Work originates from https://nava.slack.com/archives/C03G1SWD9H7/p1738089826660819
See: https://github.com/navapbc/platform-test/pull/168
=> Fix MAIL FROM and Add DMARC DNS Records

infra/project-config/aws_services.tf
n/a
see title
A project team asked for explanation of the AWS services to help justify the IAM permissions needed
n/a
=> Add comment describing each AWS service

docs/infra/module-dependencies.md
n/a
see title
We've made some changes to reduce the number of configs needed and the number of variables needed in resource modules. This change documents that change.
n/a/
=> Update module dependencies documentation

infra/{{app_name}}/app-config/env-config/outputs.tf, infra/{{app_name}}/app-config/env-config/service.tf
Just cleaning things up to be more consistent
see https://github.com/navapbc/platform-test/pull/177
=> Move service config to separate file

infra/modules/database/resources/role_manager.tf, infra/modules/service/events_role.tf, infra/modules/service/scheduler_role.tf, infra/modules/service/workflow_orchestrator_role.tf
https://github.com/navapbc/template-infra/issues/785
This PR fixes deprecation warning linked in the above ticket
see: https://github.com/navapbc/platform-test/pull/162
=> Replace `managed_policy_arns` with `aws_iam_role_policy_attachment`

infra/modules/service/variables.tf
Found while going through http://github.com/HHS/simpler-grants-gov/pull/3925/ line by line
=> Fix typo in variable description

docs/infra/pull-request-environments.md
Add some additional explanation that might be helpful. This came up when discussing PR environments with a team that's using them so I thought it'd be useful to add it to the docs.
=> Add additional docs to PR environments

docs/infra/notifications.md, infra/{{app_name}}/service/outputs.tf
Resolves #854 
see title
We should probably create a separate PR for identity provider instructions
=> Document notifications setup

.github/workflows/deploy.yml
N/A
see title
By default most projects don't want junk data in production
see https://github.com/navapbc/platform-test/pull/192
=> Don't run e2e tests on deploys to prod

docs/infra/identity-provider.md, docs/infra/notifications.md, docs/infra/pull-request-environments.md, infra/{{app_name}}/app-config/env-config/identity_provider.tf
Resolves #854 
n/a
Added identity provider a while ago but never documented it
n/a
=> Add docs on identity provider

infra/modules/network/resources/vpc_endpoints.tf
Closes https://github.com/navapbc/template-infra/issues/894
I doubt this is sufficiently complex to burn time on testing
=> Remove an evidently reference

bin/run-command
Closes https://github.com/navapbc/template-infra/issues/916
grants.gov implemented fluent-bit, and while working on that I found this
I tested this for grants.gov, I'm going to merge it here without review
=> Support sidecars in run command

.github/workflows/vulnerability-scans.yml
Update anchor scan action
See https://github.com/HHS/simpler-grants-gov/pull/5117/files
Ran anchore scan on platform-test here https://github.com/navapbc/platform-test/pull/206
=> Upgrade anchore-scan action
