- .github/PULL_REQUEST_TEMPLATE.md
* added a `.github` folder which should store all github related processes (e.g. github actions, and templates)
* added PR template
> We want to establish a consistent pull request template that we’ll use.
GitHub docs on the subject [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
New PRs should look like this after this change is added:
> WMDP-26 Set Up PR Template

- app/jest.config.js
- app/tsconfig.json
- app/tsconfig.ts-jest.json
- https://wicmtdp.atlassian.net/browse/WMDP-99
- Modifies `tsconfig.json` to use jsx mode `preserve` 
- Introduces `tsconfig.ts-jest.json` to allow ts-jest to use jsx mode `react-jsx`
Next.js requires the typescript jsx mode to be `preserve` and will make a mandatory correction when you run `yarn dev` or `yarn build` with the following message:
> The following mandatory changes were made to your tsconfig.json:
>
>	- jsx was set to preserve (next.js implements its own optimized jsx transform)
However, ts-jest needs it to be a flavor of `react`. 
For more …
> Create a separate tsconfig file to specify jsx mode for ts-jest vs next.js

- LICENSE.md
Related to https://wicmtdp.atlassian.net/browse/WMDP-83
- Adds the Apache 2.0 license as `LICENSE.md`
We want to release this work under an open source license. We have selected Apache 2.0 to maximize ease of adoptability.
> Screenshots, GIF demos, code examples or output to help show the changes working as expected. ProTip: you can drag and drop or paste images into this textbox.
N/A
> Create LICENSE.md using Apache 2.0

- .github/workflows/ci.yml
- app/.prettierignore
[WMDP-31](https://wicmtdp.atlassian.net/browse/WMDP-31)
1. Added ci.yml to run github action for pass/fail checks when pushing code to remote. Ignores merges (push) to main.
2. Added .prettierignore, which ignores generated files and list of config files see below.
1. Created initial CI.
- Ensures application successfully builds.
- Passes all lint checks.
- Passes format-check checks.
- Passes test.
2. I decided to ignore configuration files for prettier to allow someone up the chain to decide whether to format them or not.
4. Left out security scanning, it appears that was handled in [WMDP-32](https://wicmtdp.atlassian.net/browse/WMDP-32)
5. Note branch protections need to be configured separately. Three options:
- Setup manually through website
- Create 1 shot git cli command using bash …
> setup CI for NextJS template app

- README.md
N/A
- Fix broken link for github.com/new in README
The link for creating new repo was a relative link, which means if viewing from the repo's main page it will resolve to `https://github.com/navapbc/template-application-nextjs/blob/main/github.com/new`. This PR fixes it to make it a absolute URL rather than a relative one.
Tested by making change in my local editor and clicking on the link in preview mode
> Fix broken link for github.com/new in README

- app/package.json
- app/yarn.lock
- Remove `@types/testing-library__...` packages
These packages are deprecated and don't need installed. The `@testing-library/...` packages bundle their own types.
See deprecation notice on https://www.npmjs.com/package/@types/testing-library__dom
> Remove deprecated packages no longer needed

- .gitignore
No ticket, tiny one line change
- Ignore .env and .envrc in default .gitignore which can contain environment secrets
- Ignore visual studio code settings which can be developer specific
Small thing I noticed as I was going through the application setup
I don't see .env and .envrc in my untracked files anymore when running `git status`
> Ignore .env, .envrc, and VS code settings

- infra/.gitignore
- infra/README.md
- infra/bootstrap/account/.terraform.lock.hcl
- infra/envs/dev/.terraform.lock.hcl
- infra/envs/prod/.terraform.lock.hcl
- infra/envs/staging/.terraform.lock.hcl
[94](https://github.com/navapbc/template-infra/issues/94)
> Added dependency lock files
> Update doc with information related to dependency lock files
> Removed `.terraform.lock.hcl` from `.gitignore` file
Added `.terraform.lock.hcl` files to repo by running `terraform init` from appropriate working directories
Testing not required for these updates.
> add dependency lock files and update docs

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Makefile
Resolves #109 
- Add Makefile with stub commands
- Update CI to use Makefile stub commands
- Add CD workflow that calls Makefile stub commands
See [this proposal on establishing a CI/CD interface](https://github.com/navapbc/template-infra/pull/106), the idea is that the template infra would have CI/CD, then when people want to "install" a particular template application, they'll hook in the application's Makefile into the existing CI/CD.
CI and CD are not meant to be complete or necessarily even correct. They will be completed later as we implement each piece and refine the interface.
Don't know how to test CD without merging first
> Add Makefile with stub targets

- bin/bootstrap-account.sh
- bin/template-only-destroy-account.sh
- infra/bootstrap/account/main.tf
- template-only.mak
Makes progress on #122 
- Add ./bin/bootstrap-account.sh
- Add ./bin/template-only-destroy-account.sh
Eventually we want to have some template only CI that only runs on template-infra for the purposes of testing the template. This CI workflow would not be copied over to the project repo.
This PR adds the beginning pieces of that, adding scripts that are used to spin up and tear down the terraform account backend infrastructure.
Ran both scripts
> Automate account creation and destruction

- .github/workflows/template-only-ci-app.yml
- Makefile
Follow up from #106 
- Rename ci.yml to ci-app.yml 
- Remove stub make commands that weren't defined in the ADR
Cleaning up template-infra based on [this ADR](https://github.com/navapbc/template-infra/blob/main/docs/decisions/0001-ci-cd-interface.md), and renaming ci to ci-app based on [this ADR](https://github.com/navapbc/template-infra/blob/main/docs/decisions/0001-ci-cd-interface.md) and [this discussion thread](https://github.com/navapbc/template-infra/pull/106#discussion_r983854402)
> Clean up CI/CD interface

- .github/workflows/ci-infra.yml
- Makefile
- docs/compliance.md
- infra/modules/bootstrap/main.tf
- infra/modules/example/main.tf
- infra/modules/example/outputs.tf
- infra/modules/example/variable.tf
Resolves #129 
- Add infra-check-compliance target to Makefile
- Add instructions for setting up and running checkov locally
- Add compliance check to ci-infra
I thought it would be a good idea to add compliance checks to CI by default. A lot of agencies deal with security audits so having a tool like this could help with accelerating path to production.
- CI
- Also ran `make infra-check-compliance` locally:
> Add compliance check

- .github/workflows/ci-infra.yml
- Makefile
- infra/modules/bootstrap/main.tf
n/a
* Fix Makefile .PHONY targets
* Fix broken KMS key references
* Use aws_s3_bucket_logging instead of logging attribute in aws_s3_bucket
* Remove duplicate deprecated s3_server_side_encryption settings
* Add make infra-validate-modules
* Add infra validation to ci-infra workflow
When working on ECR I realized I at some point must have broken the bootstrap module, so I fixed it in this PR along with some other misc fixes and added a CI check to prevent the breakage in the future
* Ran `make -f template-only.mak bootstrap-account` and `make -f template-only.mak destroy-account`
* Added make infra-validate-modules, ran it locally and added it to ci-infra
> Fix miscellaneous issues and add validation check

- .github/workflows/template-only-ci-infra.yml
- template-only-test/template_infra_test.go
- template-only.mak
n/a
* Use unique id for infra resource names during test runs
* Remove leftover tfstate files during template-only make clean
Small improvement to make tests more isolated from each other. I'm asking Mike Moran to see if we can have separate accounts. One of the accounts I'll use for template testing, while in the other account I'll leave the backends and OIDC stuff running (rather than tearing it down after the tests) and use that to test the app infra.
Testing locally, should also pass in CI
> Use unique id during test runs

- README.md
n/a
see title
docker-compose is part of application templates now based on [slack discussion](https://nava.slack.com/archives/C03G1SWD9H7/p1666652902898639?thread_ts=1666648081.886369&cid=C03G1SWD9H7), so removing this form the instructions for now since we forgot to remove it from instructions in #151 
none
> Remove docker-compose from README instructions

- template-only-bin/install-template.sh
n/a
see title
I realize I forgot to `rm` the template-infra folder at the end of installing. Fixes bug in #177 
Ran the script and saw that it properly deleted the template-infra folder
> Clean up template infra folder at end of install

- .github/workflows/cd.yml
- Makefile
- README.md
- bin/deploy-release.sh
- bin/publish-release.sh
- template-only-docs/set-up-cd.md
Resolves #180 
* Init build-repository module before publishing
* Fix log message in deploy script
* Fix directory that terraform init runs in as part of deploy script
* Disable cd in template and add instructions for enabling
CD was failing to publish the built docker image since the build-repository module wasn't initialized. See [this run](https://github.com/navapbc/platform-test/actions/runs/3480941215/jobs/5821384944) as an example. This PR runs terraform init first as part of release-publish.
CI
> Init build-repository before publishing in CD

- app/Dockerfile
- app/start-server.sh
- infra/modules/service/container-definitions.json.tftpl
- template-only-docs/application-requirements.md
n/a
* Set PORT env var in task definition for application service
* Describe PORT env var application requirement
* Update example app to use PORT from env var
While integrating https://github.com/navapbc/template-application-nextjs with template-infra I noticed that template-application-next uses a different port (3000), and realize that as part of [12-factor app](https://12factor.net/) the applications should use the port defined by environment variables rather than hardcoding it. I fixed the nextjs template to use port from env var in [this nextjs template PR](https://github.com/navapbc/template-application-nextjs/pull/85). The current PR updates the template-infra to set the `PORT` env var in the task definition, updates the example app to also use the PORT env var, and documents the …
> Set PORT env var for application

- .github/workflows/cd.yml
- Makefile
n/a
* Authenticate with AWS in CD
* Set default environment when deploying from push event
* Limit CD concurrency based on environment being deployed to
As I was testing out CD I saw that [CD errored out](https://github.com/navapbc/platform-test/actions/runs/3516675391/jobs/5893536990) which made me realize that we didn't authenticate github actions with AWS. This PR adds that authentication.
Then as I tested again I realized that input.env_name doesn't exist on push events, so I added that as a default parameter.
Finally, as I was testing rapidly I realize that we're going to run into concurrency issues if multiple people merge to main soon after each other, so I added a concurrency limit based on the environment being deployed to.
I made these same changes in the platform-test repo and …
> Authenticate with AWS in CD

- template-only-test/template_infra_test.go
Resolves #183 
* Grop logs in template CI for readability
I noticed that it's really hard to read the template CI logs (especially for folks who isn't familiar with them), so this PR groups the template-infra-test logs to make them more readable.
Looked at the CI run and saw that the output is much more readable
> Group logs in template CI for readability

- .github/workflows/cd.yml
- template-only-docs/set-up-cd.md
n/a
* Templatize github actions role ARN in cd workflow
* Add instructions to set-up-cd to update github actions role ARN
I just realized I hardcoded the github actions ARN, it should be templatized
n/a
> Templatize github actions role ARN in cd workflow

- infra/modules/service/container-definitions.json.tftpl
- infra/modules/service/main.tf
- template-only-docs/application-requirements.md
Resolves #205 
* Fix container healthcheck to use wget rather than curl which isn't available in the container
* Fix ALB healthcheck to use port variable rather than hardcoded port
I noticed sometimes the deployed test services would sometimes return 503. After some investigation, it looks like the container and ALB healthchecks weren't configured properly. This PR fixes those.
Made the fixes on the [platform-test](https://github.com/navapbc/platform-test) repo and saw that it fixes things:
Load balancer target group now shows healthy hosts:
And ECS shows task as healthy
> Fix healthchecks

- Makefile
- template-only-bin/install-template.sh
{LINK TO TICKET}
- Added the image scanner config files to the `template-only-bin/download-and-install-template.sh` file so that any repos that use the scanners will have them
- Added make command to run the above script
- Added make commands to check changes from last commit (`get-last-changes` and `get-last-changes-summary`)
- Added make commands to check changes since last pull from main (`get-local-changes` and `get-local-changes-summary`)
The main point of this PR was to setup the image scanner configs to be copied when running the template script. I added the make commands as a QoL improvement as well so that you can run the command to update the repo if you have already pulled it. The other make commands were just so that people can see the changes they have since their last pull …
> Add scanner config files to update script and added helper commands

- template-only-bin/update-template.sh
n/a
see title 
Flask and Nextjs each have different scanner configs so the template should copy over the template on initial install but not overwrite it when updating the template
I didn't do testing but the change I think is simple enough, and low-risk / reversible
> Don't overwrite project scanner configs on update

- .github/workflows/template-only-ci-infra.yml
- infra/modules/container-image-repository/main.tf
N/A
see title
It looks like assigning `kms_key = key_id` causes the terraform plan to detect a change. We need to be using the ARN instead:
With key_id
With arn
Ran terraform plan in `platform-test` repo with and without the change
> Use kms arn instead key_id of to avoid forcing replacement

- .github/workflows/template-only-ci-infra.yml
n/a
see title
We're having issues getting CI to pass so this change allows us to manually run it from main to try to get a clean run.
CI shows a clean run
> Allow manual run of template-only-ci-infra

- bin/publish-release.sh
https://github.com/navapbc/template-infra/issues/197
Check if the image tag exists in AWS ECR. If so, do not republish
On a Deploy failure, the image tag may get uploaded, resulting in a failure when the re-run tries to create a duplicate tag. This work will check for that tag first.
https://github.com/navapbc/platform-test/pull/5
> Check if image tag exists prior to build/publish

- .github/workflows/cd.yml
https://github.com/navapbc/template-infra/issues/198
Added specific paths to trigger deploy
The deploy workflow should only be triggered when a file under specific paths is updated
N/A
> Deploy from main branch only from specific paths

- infra/modules/service/main.tf
Resolves #264 
see title
We had some stuff in the service module that would force a replacement of the task definition regardless of whether anything changed. This change fixes that by adding some values in the container definition that AWS was setting default values for.
I made this change in platform-test and ran `terraform plan` before and after the change. After the change the plan became clean/empty.
`terraform plan` in `infra/app/envs/dev` on platform-test repo before change (on `main`):
After change:
See the PR in platform-test https://github.com/navapbc/platform-test/pull/8 to see that the change also passes all the CI checks in platform-test
> Define healthCheck params to avoid force replace

- template-only-docs/application-requirements.md
N/A
see title
Looks like one of the links was broken/outdated
New link works: http://app-dev-1582588227.us-east-1.elb.amazonaws.com/
> Fix endpoint link

- Makefile
Resolves #263 
see title
This change improves the developer experience by adding
parameter checks to the Makefile so a developer can more
easily remember fix their Make command without having to
look into the Makefile itself
Ran the commands without passing in params
CI still works (CI runs the commands with the parameters)
> Add make target parameter checks

- template-only-bin/update-template.sh
Resolves #279 
see title
The template-only-cd.yml workflow is buggy. It currently overwrites .github/workflows/ci-infra.yml, which causes the infra e2e tests to be commented out. As an example, see this latest commit on platform-test: https://github.com/navapbc/platform-test-nextjs/commit/5b8b9f22d2c4bb5ca4f9717adde60b51c49dffb9#diff-c871e126464447bfd392c61d9679ad5715b9bb292caa88dd214e27bc5ae46075
This change adds ci-infra.yml to the list of files not to touch during the CI deploy's update-template.sh step.
Didn't test this since it's a low risk change to make
> Don't overwrite ci-infra on template deploy

- bin/set-up-current-account.sh
Resolves #291 
see title
Encountered this bug while testing with `us-west-1`
Made the same change in my test account and re-ran `make infra-set-up-account` and it got past the s3 bucket creation step:
> Add location for buckets outside of us-east-1

- infra/accounts/main.tf
- infra/app/build-repository/main.tf
- infra/app/service/main.tf
N/A
see title
Elsewhere in the codebase we have `required_version = ">=1.2.0"` but for accounts it's `~>1.2.0` which is too restrictive, especially since we require 1.4.6 as part of the database work.
I ran into this issue while testing out the template infra on a test account while running `make infra-set-up-account`:
Made the same change in my test repo and re-ran `make infra-set-up-account` and saw that it succeeded
> Relax terraform core version constraint

- bin/set-up-current-account.sh
N/A
Fix regression introduced by #292
I was careless and didn't test for us-east-1 after fixing for us-west-1 since I assumed CI ran but it actually didn't until merged to main. This change fixes the regression.
(As an aside, I think it's silly that the AWS CLI interface requires this separate parameter for regions different from us-east-1 but doesn't allow it for us-east-1)
1. Configured project-config/main.tf to use us-east-1
2. Ran `make infra-set-up-account ACCOUNT_NAME=dev`
3. Destroyed everything with `make -f template-only.mak destroy-account`
Cleaned up the repo and did the following steps for testing us-west-1:
1. Changed my AWS config to default to us-west-1
2. Changed project-config/main.tf to use us-west-1 as default region
3. Ran `make infra-set-up-account ACCOUNT_NAME=dev` …
> Fix regression for us-east-1

- .github/workflows/template-only-cd.yml
Resolves #306 
see title
The template CD currently deploys to the integration test repos platform-test and platform-test-nextjs. This PR adds a new integration platform-test-flask.
Manually triggered the workflow from this branch https://github.com/navapbc/template-infra/actions/runs/5225329852
> Deploy to platform-test-flask as part of CD

- template-only-bin/update-template.sh
n/a
see title
In #297 we extracted build-and-publish to a separate workflow but I forgot to add that workflow to the list of files we restore in update-template.sh. If we don't list that file in update-template.sh, then every time we merge something to main in template-infra, we'll overwrite the role-to-assume variable in the file for all the test projects (platform-test, platform-test-nextjs, and platform-test-flask)
> Don't overwrite build-and-publish in update.sh

- bin/run-database-migrations.sh
n/a
see title
Most of the env vars in run-database-migrations.sh are already defined in the container task definition. The only one that needs to be overwritten is DB_USER, which should be set the user to the migrator user rather than the app user.
Ran migrations script locally on the platform-test repo after making these changes in this PR: https://github.com/navapbc/platform-test/pull/18
Here are the logs from the migration run:
> Remove unnecessary env vars from run-database-migrations script

- infra/modules/database/main.tf
- infra/modules/database/role_manager/role_manager.py
Resolves #326 
* Connect to app database rather than postgres database when creating schema and roles
We were getting a migration error when running the flask template migrations with the template infrastructure. The migration error says
> sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) no schema has been selected to create in
It turns out that the role_manager that created the schema and roles created them in the wrong database, so when the application migrations task connected to the correct database and tried to run migrations, the schema it was expecting to exist didn't actually exist.
This change fixes this by connecting the role manager to the correct database. It also changes the way the role manager accesses environment variables to fail immediately if any …
> Create schema and roles in correct database

- app/db-migrate
- infra/modules/database/main.tf
- infra/modules/database/role_manager/role_manager.py
n/a
see title
PR #327 fixed an issue that wasn't detected on the platform-test repo since platform-test didn't specify the search path when logging in to the database, so the migrations table still created successfully on the `public` schema.
This change specifies the search path to restrict table creations to the app schema as specified by the DB_SCHEMA environment variable
developed and testing the change on the platform-test repo by running the Deploy workflow directly from the feature branch: see PR https://github.com/navapbc/platform-test/pull/21
Ran deploy manually from the branch on platform-test
> Specify search_path during example app migrations

- .github/workflows/ci-vulnerability-scans.yml
{LINK TO TICKET}
- Changed from `table` to `json` format on the Trivy scan
After the change to display findings in the summary page, the [template NextJS repo](https://github.com/navapbc/platform-test-nextjs/actions/runs/5404489689) is failing, and it looks to be because of how the Trivy scan is formatting its findings. The `table` format is 2.1MB, so it can't be displayed in the summary, and fails because of that. Upon pulling that file up, there is a single row in the table, and is extremely long to where it isn't very legible. 
I tested all of the format options, and here is what I saw
- `table` -> File is too large and fails because of this, but locally has findings
- `json` -> Has findings, file size is 4.6KB, output is JSON, findings are in `Results` row of object
- `github` -> Has …
> Fix Trivy scan format

- .github/workflows/cd.yml
Resolves #317 
see title
A lot of times for development and testing we need to manually trigger deploys so I thought this would be good to do sooner than later to improve the developer experience of working on the platform.
To test this I just manually triggered the deploy script directly on this template repo since I don't really care if the deploy itself succeeds. Just trying to see if the name is rendered properly, not changing anything else about the workflow.
Here's the manual run I triggered: https://github.com/navapbc/template-infra/actions/runs/5351170243
> Add branch and environment to deploy run name

- infra/modules/auth-github-actions/main.tf
Resolves #338 
see title
Recently some workflows started failing with an error:
> Error: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
(e.g. [this run](https://github.com/navapbc/platform-test-nextjs/actions/runs/5404401054/jobs/9818514745))
Based on Amazon's docs – https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html – the OIDC provider thumbprint should be obtained from the last certificate in the chain, not the first one. Here's the relevant excerpt:
> If you see more than one certificate, find the last certificate displayed (at the end of the command output). This contains the certificate of the top intermediate CA in the certificate authority chain.
I made the change on platform-test-nextjs repo and …
> Get github oidc thumbprint from last certificate

- .github/workflows/ci-vulnerability-scans.yml
- trivy-secret.yaml
Resolves https://github.com/navapbc/template-application-nextjs/issues/165
* Disable alibaba secret scanning
* Output trivy scans to table format
Vulnerability scans were failing for platform-test-nextjs.
First, I needed to output not to a file since the runs weren't showing any output. See https://github.com/navapbc/platform-test-nextjs/actions/runs/5418384398
So I made the logs output to stdout instead of to a file. And I changed back to table format which is better than JSON.
It turns out the reason for the failure was a false positive scan for alibaba secret.
Since I don't see any situation where our project would be using alibaba I figure we should disable it. Trivy recommends specifying either enable rules or disable rules: …
> Disable alibaba secret scanning

- bin/configure-app-service.sh
n/a
see title
I just noticed that there was this variable in configure-app-service.sh that was defined but never used, so this PR is to just clean that up
Just relying on CI for testing this change
> Remove unused variable

- docs/decisions/infra/0002-use-custom-implementation-of-github-oidc.md
- infra/modules/auth-github-actions/main.tf
Resolves #348 
see title
On July 11, 2023, we received an IAM security notification that explains that the GitHub OIDC identity provider's TLS intermediate certificate thumbprint(s) no longer need to be specified in AWS OIDC configuration since GitHub's root certificate is now trusted by AWS. Here is the relevant excerpt:
> Starting July 6, 2023, AWS began securing communication with GitHub’s OIDC identity provider (IdP) using our library of trusted root Certificate Authorities instead of using a certificate thumbprint to verify the IdP’s server certificate. This approach ensures that your GitHub OIDC configuration behaves correctly without disruption during future certificate rotations and changes. With this new validation approach in place, your legacy thumbprint(s) will remain in your …
> Remove GitHub OIDC TLS certificate thumbprint

- Makefile
- bin/run-database-migrations.sh
n/a
see title
I accidentally broke db migrations (see failed run: https://github.com/navapbc/platform-test/actions/runs/5580152070)
It's because I missed the one reference to the database layer output that I deleted in #355 
This change makes the db migrations script get the migrator user from the db config rather than from the db layer output which no longer exists.
I tested this out on platform-test repo after making the changes I ran `make release-run-database-migrations APP_NAME=app ENVIRONMENT=dev`, and here are the logs showing the successful migration
> Fix db migrations script

- .github/workflows/template-only-ci-infra.yml
- bin/set-up-current-account.sh
- infra/accounts/main.tf
Resolves #259 
* Upgrade AWS provider version for infra/accounts to 5.6.0
* Remove retry loop workaround
A fix for a race condition in the Terraform AWS provider has been merged. The fix was in this PR: https://github.com/hashicorp/terraform-provider-aws/pull/30916 and was released as part of AWS provider version 5.6.0.
> Remove workaround for aws_s3_bucket_logging race condition

- Makefile
Resolves #356 
see title
Can you see if these commands are intuitive for you
> Add make help comments

- docs/infra/set-up-database.md
- infra/app/database/outputs.tf
- infra/modules/database/main.tf
- infra/modules/database/outputs.tf
I think this output was missing? Not super familiar with Terraform. 
When I was following the instructions to setup the DB, I ran into a warning about no outputs when I ran `make infra-update-app-database-roles APP_NAME=app ENVIRONMENT=<ENVIRONMENT>`
The make script internally runs `terraform -chdir=infra/$APP_NAME/database output -raw role_manager_function_name`.
Before this change:
After this change:
> Add maybe missing database outputs

- template-only-test/template_infra_test.go
n/a
see title
We were grouping all the other logs but didn't group the logs for when we spun up the web service, so it was really noisy.
[Before:](https://github.com/navapbc/template-infra/actions/runs/5767379754/job/15636950869#step:6:1362)
[After:](https://github.com/navapbc/template-infra/actions/runs/5790516517/job/15693714116?pr=370#step:6:1360)
Now the entire run fits in one screenshot, with the ability to expand
> Group template test logs for web service testing

- infra/modules/monitoring/main.tf
Alert attribute treat_missing_data = "notBreaching" added for 5xx errors. Alerts should change status to OK when there are no errors.
> fix: remove attribute causing alerts breach when there is not data

- docs/infra/set-up-database.md
n/a
Very slight tweak to documentation that the app name variable in the command can/should be changed, much like `<ENVIRONMENT>`
> Update set-up-database.md to clarify that APP_NAME can be changed

- app/app.py
- app/migrations.sql
- docs/infra/set-up-database.md
- infra/modules/database/role_manager/role_manager.py
Resolves #{TICKET NUMBER OR URL}
- Revert previous change that didn't properly fix table permissions
- Add migrations route to test app to test access to a table created by migrator
- Update migrations file to alter default privileges for tables created by migrator role
- Update instructions to explain the gotcha
We recently merged #373 to attempt to fix an issue with table privileges but that didn't actually solve the problem. This PR removes the previous change and shows an example of a proper fix that needs to be implemented in the application migrations, updates the example app's migrations, and added instructions in the db-setup to call this gotcha out.
Tested this out on platform-test repo https://github.com/navapbc/platform-test/pull/26
> Explain how to fix default table permissions in app

- .github/workflows/ci-infra-service.yml
- .github/workflows/ci-infra.yml
- Makefile
- infra/modules/service/access_logs.tf
- infra/test/helpers.go
- infra/test/infra_test.go
- template-only-bin/update-template.sh
- template-only-docs/set-up-ci.md
n/a
* Add helpers.go file for helper functions for tests
* Create TerraformInit helper function
* Rename TestDev to TestService
* Separate service e2e infra tests into its own ci-infra-service.yml workflow
* Rename make infra-test to make infra-test-service
This is in preparation to add db tests. Databases take too long to spin up and down so I want to have separate CI job for db that only runs when there are changes to db files.
I did the refactoring in a PR in platform-test and the CI checks still run and pass. See this PR: https://github.com/navapbc/platform-test/pull/30
The small differences in line changes between this PR and the one in platform-test are due to:
* the fact that the infra tests start out commented out in template-infra
* the updates to template-only-docs/set-up-ci.md
> Refactor infra tests to prepare for db tests

- Makefile
Resolves #391 
- Remove default for `APP_NAME`
- Anywhere `APP_NAME` is required, do a check
- Add ENVIRONMENT check to release-run-database-migrations
- `IMAGE-NAME` also requires `APP-NAME`
Hopefully I got them all! I didn't test every single command locally. This is overall better for apps that rename the `/app` directory or monorepo structures so that there is no confusion.
> Require APP_NAME in relevant make commands

- .github/workflows/cd-app.yml
n/a
see title
Tweak workflow names to be more consistent with each other. I think the deploy workflows should be next to each other
didn't test, the change seems simple enough
> Tweak cd workflow name

- infra/modules/service/access-logs.tf
N/A
- Remove bucket versioning for access logs
- Add checkov skip to work for CI
- Does not directly interact with app functionality
> Log files are immutable. Versioning makes it more difficult to clean up failed tests. 
- Successfully deploys and passes all CI checks in platform-test
> Remove versioning on access log bucket

- .github/workflows/template-only-cd.yml
- template-only-bin/download-and-install-template.sh
- template-only-bin/update-template.sh
Work for #352 
* After running install-template.sh or update-template.sh on a project, store the template version in a .template-version file
* Add TARGET_VERSION parameter to update-template.sh
* Switch update-template.sh script to clone template-infra repo
* Remove redundant checkout of template-infra repo from template-only-cd
This is the first PR for #352 that will create the .template-version files in platform test repos.
A subsequent PR will refactor update-template.sh to creating and apply git patches rather than simply copying and restoring files.
Ran this branch's version of update-template.sh from platform-test repo via the command
```
curl https://raw.githubusercontent.com/navapbc/template-infra/lorenyu/update/template-only-bin/update-template.sh | bash -s
```
and saw that it …
> Store template version in a file on project

- template-only-bin/update-template.sh
n/a, this is a quick fix from bug introduced in #402 
see title
Turns out git clone using SSH within a github action is more complicated and breaks. See broken run:
https://github.com/navapbc/template-infra/actions/runs/5978963936
Ran template deploy from this branch: https://github.com/navapbc/template-infra/actions/runs/5979055015 it now succeeds
> Use https not ssh for git clone in update-template.sh

- Makefile
- infra/networks/default.s3.tfbackend
- infra/networks/main.tf
- infra/project-config/main.tf
- infra/project-config/outputs.tf
Prerequisite work for #277 
* Add basic infra/networks module with:
* VPC endpoints for AWS services
* security group for VPC endpoints
* Add make infra-configure-network
* Add make infra-update-network
This is step 1 for migrating VPC endpoints to a separate networks module. This is needed in order to add database infra tests, since currently VPC endpoints are created in the db module, but there can only be one VPC endpoint for a particular AWS service per VPC, which prevents us from creating a parallel database cluster in a separate terraform workspace.
This step creates a new networks module that will create the VPC endpoints and the security group
for those endpoints.
As part of rolling this out, we need to import the existing VPC endpoints to the new networks module.
The security …
> Migrate VPC endpoints to separate networks module (step 1)

- docs/infra/set-up-app-env.md
- docs/infra/set-up-network.md
- infra/app/database/main.tf
- infra/modules/database/main.tf
- infra/modules/database/networking.tf
- infra/modules/database/variables.tf
- infra/networks/main.tf
Work for #277 
* Replace VPC endpoints in database module with data sources referencing VPC endpoints created in network module
This is the second part of migrating VPC endpoints to the network module from the database module
As part of rolling out https://github.com/navapbc/template-infra/pull/405 we imported VPC endpoints to a separate networks module, so as part of rolling out this module, we need to [terraform rm](https://developer.hashicorp.com/terraform/cli/commands/state/rm) the VPC endpoints from the database module before applying on platform-test and platform-test-flask:
```bash
terraform -chdir=infra/app/database state rm module.database.aws_vpc_endpoint.kms
terraform -chdir=infra/app/database state rm module.database.aws_vpc_endpoint.ssm
make infra-update-app-database …
```
> Migrate VPC endpoints to separate networks module (step 2/2)

- docs/infra/set-up-app-env.md
- template-only-docs/application-requirements.md
Not applicable.
- Fix broken link to application requirements (will not work after installing template)
- Mention installation scripts for current template applications
The broken link increased the difficulty of deploying code for a bid. This will reduce the likelihood that we will run into the same issue if we need to setup another version of the same repository for the bid.
This also mentions the relevant details (the application setup scripts) directly in this repo's documentation to improve visibility.
Not applicable.
> Fix broken link; improve template application usage instructions

- bin/run-command.sh
- bin/run-database-migrations.sh
- infra/app/service/outputs.tf
- infra/modules/service/main.tf
- infra/modules/service/outputs.tf
Resolves #320 
* Add application_log_group and application_log_stream_prefix to service layer outputs
* Update run-command to print task logs every second while the task is running until it completes
When running database migrations, the logs from the migration are currently in CloudWatch. It would be more convenient for developers to see the logs directly in the GitHub actions workflow. This change makes that possible.
Development and testing on platform-test repo https://github.com/navapbc/platform-test/pull/29
> Show CloudWatch logs in run-command.sh

- template-only-bin/update-template.sh
n/a
see title
I needed to exclude cd.yml and ci-infra.yml for testing purposes when doing #403, but it is no longer necessary to exclude that from the list of files we patch
> Note that I had to temporarily exclude cd.yml and ci-infra.yml for testing, since those files included big changes that don't apply well. In the future, only changes to the commented out sections of those files would have issues with patching.
Did a basic sanity test check by running on platform-test's main branch the version of update-template.sh on this branch via
```
platform-test$ curl https://raw.githubusercontent.com/navapbc/template-infra/lorenyu/updateexclude/template-only-bin/update-template.sh | bash -s
```
note the branch name in the command
(there were no changes of course since platform-test is already …
> Remove cd.yml and ci-infra.yml from update-template exclude list

- docs/infra/vulnerability-management.md
N/A
- Fix typo: `trivy scanner` should be `hadolint scanner` in the Hadolint section
Refer to `hadolint-scan` job: https://github.com/navapbc/template-infra/blob/yoom/fix-hadolint-typo/.github/workflows/ci-vulnerability-scans.yml#L27
N/A
> Fix hadolint typo in vulnerability-management.md

- infra/app/app-config/env-config/outputs.tf
n/a
see title
everywhere else in infra code we reference the noun migrator not the verb migrate.
it'll be much easier to rename this now before it's being used by the service in https://github.com/navapbc/template-infra/pull/411/files
i didn't actually test this
will need to run `make infra-update-app-database APP_NAME=app ENVIRONMENT=dev` on all the platform test repos
> Rename migrator policy to be consistent

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/check-infra-auth.yml
- .github/workflows/template-only-ci-infra.yml
Resolves #243 
see title
There was a maintenance ticket to switch to v2 of aws-actions/configure-aws-credentials, but turns out they released v3 already. This change switches to using that.
CI should cover at least the changes in check-infra-auth.yml and template-only-ci-infra.yml, and the change in actions/configure-aws-credentials/action.yml is similar enough to the other two and also low risk enough that I don't think it's worth explicitly testing that one. If https://github.com/navapbc/template-infra/pull/415 gets merged first, then CI will also automatically cover all three changes.
> Use v3 of aws-actions/configure-aws-credentials

- bin/run-command.sh
n/a
see title
I saw that we hit the rate limit for describe-log-streams in this run in the platform-test-flask account https://github.com/navapbc/platform-test-flask/actions/runs/6099419118/job/16551627018
This PR reduces the polling frequency to hopefully reduce the chance that this rate limit will be hit
Didn't test since this is just a config change of a single number
> Reduce polling frequency for describe-log-streams

- infra/modules/service/access-control.tf
- infra/modules/service/database-access.tf
- infra/modules/service/outputs.tf
n/a
see title
The migrator task role isn't needed for projects that don't have a database
Developed and tested on a project with has_database = false i.e. platform-test-nextjs (see https://github.com/navapbc/platform-test-nextjs/pull/81) and a project with has_database = true i.e. platform-test (see https://github.com/navapbc/platform-test/pull/43)
> Don't create migrator role if has_db is false

- .github/workflows/ci-infra-service.yml
- infra/test/infra_test.go
n/a
see title
About half of the logs were grouped for infra CI service tests, and the other half weren't grouped, making the logs still hard to read. This change groups the rest of the logs.
developed and tested on platform test in https://github.com/navapbc/platform-test/pull/44
> Group logs in infra CI service tests

- infra/modules/service/access-control.tf
n/a
see title
There was resource cycling on main branch due to the conflict between [the inline managed_policy_arns block](https://github.com/navapbc/template-infra/blob/057c763b1a24f076f2c57775cb73eaa02d052be5/infra/modules/service/access-control.tf#L21-L23) and the [policy attachment](https://github.com/navapbc/template-infra/blob/057c763b1a24f076f2c57775cb73eaa02d052be5/infra/modules/service/database-access.tf#L24-L29). This PR removes the inline block which was conflicting.
dev and testing on platform test in https://github.com/navapbc/platform-test/pull/48
> Remove conflicting empty managed policy block

- bin/run-database-migrations.sh
n/a
see title
When merging [#42](https://github.com/navapbc/template-infra/pull/433) there was one place that was doing a terraform apply on the infra/app/service layer that I didn't update, which resulted in a failure when running db migrations (see failed run: https://github.com/navapbc/platform-test/actions/runs/6118143457/job/16605796551)
Failed with this error
```
│ Error: No value for required variable
│ 
│   on variables.tf line 1:
│    1: variable "environment_name" {
│ 
│ The root module input variable "environment_name" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
```
This change fixes that by having the run-database-migrations.sh script call the `make infra-update-app-service` target rather than …
> Use make command in run db migrations

- bin/deploy-release.sh
n/a
see title
This fix https://github.com/navapbc/template-infra/pull/435/files fixed migrations, but now the last step of the deploy (deploy release) fails for the same reason that the migrations failed (see failed run: https://github.com/navapbc/platform-test/actions/runs/6124192950). This change applies the same fix to the deploy release step.
developed and tested on platform test in this PR https://github.com/navapbc/platform-test/pull/50
> Fix deploy release

- Makefile
n/a
see title
In https://github.com/navapbc/template-infra/pull/433 we switched the make infra-update-app-database and make infra-update-app-service commands to use terraform init directly rather than the terraform-init-and-apply.sh script. During that transition we didn't port over the -reconfigure option which is needed when switching around between different backend configurations (e.g. between different environments). This change fixes that.
developed and tested on platform-test in https://github.com/navapbc/platform-test/pull/52
> Fix: add -reconfigure to tf init call

- bin/run-command.sh
Related to #354
* Refactor environment variables parameter for run-command to use --environment-variables optional flag
* Add --task-role-arn option to override task role
> Necessary for separation of database roles
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/47
> Add option to override task role in run-command.sh

- bin/run-database-migrations.sh
Resolves https://github.com/navapbc/template-infra/pull/440
see title
In https://github.com/navapbc/template-infra/pull/440 we added an option to override task role but also changed the way the run-command script accepts environment variables, which broke migrations. This change fixes that.
developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/53
> Fix run-database-migrations

- bin/run-database-migrations.sh
- infra/app/service/outputs.tf
Work for https://github.com/navapbc/template-infra/issues/354
* Add migrator_role_arn to service layer outputs
* Use migrator role when running migrations
Part 3 or 4 of task to separate db roles. Use the migrator role when running migrations.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/54
> Use migrator role when running migrations

- infra/app/app-config/dev.tf
- infra/app/app-config/main.tf
- infra/app/app-config/prod.tf
- infra/app/app-config/staging.tf
Resolves #425 
see title
The current app-config doesn't make it obvious how to have separate config values for each environment. This change refactors app-config to have separate config blocks for each environment which will probably be the more common scenario rather than the scenario where every environment is identically configured.
Developed and tested on platform-test in this PR: https://github.com/navapbc/platform-test/pull/51
> Refactor env configs into separate blocks

- .github/actions/configure-aws-credentials/action.yml
- bin/configure-monitoring-secret.sh
- bin/publish-release.sh
- bin/run-database-migrations.sh
- bin/set-up-current-account.sh
Resolves #412 
Replaced deprecated `terraform refresh` with `terraform apply -refresh-only`
Based on this [platform-test PR](https://github.com/navapbc/platform-test/pull/56)
Terraform refresh is deprecated and is known to have stability issues.
All changed files have been tested in platform test
>  Replace refresh with apply refresh

- .github/workflows/build-and-publish.yml
- docs/code-reviews.md
Resolves #427 
- Add `concurrency` key to stop race condition for multiple runs on same branch
- Uses github action and commit hash
+ Action because only concurrent runs of same action is an issue
+ commit hash because that's the image tag and causes conflict
Prevents race condition in which second job fails due to naming conflict
Tested in [platform-test](https://github.com/navapbc/platform-test/pull/57)
> Add concurrency limit to build and publish

- infra/modules/database/role-manager.tf
Resolves #446
- Causes pip install to occur on every apply
- Done using `timestamp()` for `trigger_replace` value
Done to prevent case where second engineer in repo can make deployment without lambda dependencies
Tested in [platform-test PR](https://github.com/navapbc/platform-test/pull/58)
> Install role manager dependencies on every apply

- infra/modules/database/backups.tf
- infra/modules/database/main.tf
- infra/modules/database/monitoring.tf
Resolves #455 
- Rename the database backup IAM role prefix
- Rename the database enhanced monitoring IAM role prefix
I've gotten this kind of error multiple times:
```
│ Error: expected length of name_prefix to be in the range (1 - 38), got rocket-experiment-dev-enhanced-monitoring-
│
│   with module.database.aws_iam_role.rds_enhanced_monitoring,
│   on ../../modules/database/monitoring.tf line 6, in resource "aws_iam_role" "rds_enhanced_monitoring":
│    6:   name_prefix        = "${var.name}-enhanced-monitoring-"
│
```
It originates here: …
> Shorten database IAM role name prefixes due to character limits

- infra/modules/database/role-manager.tf
- infra/modules/database/role_manager/role_manager.py
Resolves #475 
* Fix "invalid count argument" error
Additional changes
* Remove "password_ts" event from role manager lambda
* Merge redundant IAM policies for role manager ssm access
* Clean up DEBUG log level configuration in role manager
In https://github.com/navapbc/template-infra/issues/475, @rocketnova discovered a bug that prevents terraform from creating a plan for the database layer. The module sets the count for the db password secret to be `length(aws_rds_cluster.db.master_user_secret)`, but this is unnecessary since `aws_rds_cluster.db.master_user_secret` will always be available as long as the rds_cluster's `manage_master_user_password` is set to `true` which will always be the case since it is hardcoded to `true` (see …
> Fix "invalid count argument" error

- Makefile
- docs/infra/set-up-app-env.md
N/A
- Removed a Makefile comment
- Updated documentation
The Makefile no longer defines `APP_NAME`, so the comment is no longer correct. Running `make infra-update-app-service` also prints out the incorrect comment:
```
$ TF_CLI_ARGS_apply="-var=image_tag=58d85d736f36d503035e5c526e1df5cbf512dc44" make infra-update-app-service APP_NAME=app ENVIRONMENT=dev
terraform -chdir="infra/app/service" init -input=false -reconfigure -backend-config="dev.s3.tfbackend"
Initializing the backend...
<etc>
```
Updated the `set-up-app-env.md` documentation to reflect that you need to define `APP_NAME`
> Provide …
> Update some documentation around APP_NAME

- template-only-bin/destroy-app-service.sh
Resolves #470 
see title
@shawnvanderjagt pointed out that when there's an error in the service layer's apply, then the subsequent apply to enable force_destroy will also fail, causing the service layer to not properly cleanup. This change does something slightly different than what Shawn suggested in his ticket but should be a similar level of improvement. Rather than move the force_destroy enabling to before the service layer apply, instead use a targeted apply to enable force_destroy, which should work in most cases.
CI should cover this change.
> Use targeted apply when enabling force_destroy

- .github/workflows/cd-app.yml
- Makefile
- docs/infra/set-up-app-env.md
- docs/infra/set-up-network.md
- infra/README.md
- infra/app/app-config/dev.tf
- infra/app/app-config/env-config/outputs.tf
- infra/app/app-config/env-config/variables.tf
- infra/app/app-config/main.tf
- infra/app/app-config/prod.tf
- infra/app/app-config/staging.tf
- infra/app/database/main.tf
- infra/app/service/main.tf
- infra/modules/database/main.tf
- infra/modules/database/role-manager.tf
- infra/modules/database/variables.tf
- infra/modules/network/main.tf
- infra/modules/network/outputs.tf
- infra/modules/network/variables.tf
- infra/modules/service/load-balancer.tf
- infra/modules/service/main.tf
- infra/modules/service/networking.tf
- infra/modules/service/variables.tf
- infra/networks/main.tf
- infra/networks/variables.tf
- infra/project-config/main.tf
- infra/project-config/outputs.tf
- template-only-bin/destroy-network.sh
- template-only-test/template_infra_test.go
- template-only.mak
Resolves #152 
* Add network configuration object in `project-config` mapping network names to network-specific configs
* Currently the only configurable thing is the name of the database subnet group. Everything else is hardcoded to use defaults
* Add `infra/modules/network` module that creates a nondefault VPC with a basic default configuration that contains:
* 3 availability zones
* 3 public subnets to be used by the load balancer
* 3 private subnets to be used by the application layer
* 3 database subnets to be used by the database layer
* database subnet group containing the database subnets to be used by Amazon RDS Aurora
* optional NAT gateway configurations
* Modify the network layer (`infra/networks/main.tf`):
* Call `infra/modules/network` to create non-default VPC
* Add VPC …
> Create non-default VPC in network layer

- .github/workflows/ci-docs.yml
- .github/workflows/markdownlint-config.json
- Makefile
- README.md
- bin/lint-markdown.sh
- docs/infra/set-up-infrastructure-tools.md
- template-only-docs/application-requirements.md
Resolves #490
* Add a lint `make` target for markdown files. Add a linter that checks for broken links.
* Fix broken link in markdown files found by this linter.
PLEASE: double check the fixed links to ensure I found the right one. 🙂 
This linter only checks broken links. There are other markdown linters we can consider adding should the need arise. This linter will be run when running the specific make command `make infra-lint-markdown` as well as the general lint command `make infra-lint`. Therefore, it will also be picked up as part of the CI pipeline which runs all the linters.
For the action, I largely copied the action used in [GoogleChrome](https://github.com/GoogleChrome/lighthouse/blob/main/.github/workflows/cron-weekly.yml).
Running locally before fixing the errors (snippet …
> Lint markdown files for broken links.

- template-only-docs/application-requirements.md
n/a
* Remove link to live running test app. This link is prone to breaking and the updated one can be found in the repo where the source code lives.
[Slack thread with some discussion](https://nava.slack.com/archives/C03G1SWD9H7/p1702049486379949).
Trivial doc change. I believe existing linters are adequate testing.
> Remove link to live running app.

- .github/workflows/markdownlint-config.json
Some templates include links to localhost when communicating where something can be viewed when the application is running locally.
> Ignore linting localhost Markdown links

- docs/infra/set-up-database.md
The linked file doesn't exist when a project installs the infra and flask templates into a repo. This causes the Markdown link checker to fail on the project.
> Fix broken Markdown link when template is installed

- Makefile
- bin/lint-markdown.sh
- docs/infra/set-up-infrastructure-tools.md
- Renamed the Make target from `infra-lint-markdown` to `lint-markdown`, since when a project copies templates into a repo, this linter runs across the entire repo and not just the `infra` directory
- Use `npx` to execute `markdown-link-check` which will automatically offer to install the package if it's missing. `npx` is bundled alongside `npm`
> Update markdown linter name and execution

- infra/test/infra_test.go
- template-only-test/template_infra_test.go
N/A
* Hit feature-flags endpoint in example app during CI Infra tests
[This commit](https://github.com/navapbc/template-infra/commit/8bfab4387277bb7789d1aebc062bb3f6ba9a1e1d) broke the feature flag evidently integration (fixed now) but it was not caught as part of any automated testing. This change adds a ping to the feature-flags endpoint which integrates with Evidently to catch future regressions.
This PR will trigger template-only-ci-infra.yml which has one of the changes.
[This other PR in platform-test](https://github.com/navapbc/platform-test/pull/77) will trigger ci-infra-service.yml which has the other change.
The two CI runs should cover these changes since these are only changes to the tests.
> Test feature flag endpoint in CI

- app/Dockerfile
- app/app.py
- app/db.py
- app/feature_flags.py
- app/storage.py
- infra/app/service/main.tf
- infra/modules/storage/access-control.tf
- infra/modules/storage/encryption.tf
- infra/modules/storage/events.tf
- infra/modules/storage/lifecycle.tf
- infra/modules/storage/main.tf
- infra/modules/storage/outputs.tf
- infra/modules/storage/variables.tf
- infra/test/infra_test.go
- template-only-bin/destroy-app-service.sh
Resolves #508 
* Add new module infra/modules/storage that creates a bucket for uploading documents
* Add document_upload endpoint to example app that allows a user to upload a document to the bucket
* Split example app into separate files
* Update CI infra to delete the bucket properly
It is common for applications to need a place to store documents. The documents can be user uploaded documents to be processed by the system, or documents from other systems that are used for ETL pipelines. This change adds the bucket and an example app endpoint that leverages the bucket to upload a document.
Also, the app.py file for the example app was getting long so I split it up into separate files.
Developed and tested on platform-test in https://github.com/navapbc/platform-test/pull/76
> Add storage module for uploading documents

- infra/modules/network/vpc-endpoints.tf
n/a
* Replace hardcoded list of Evidently AZs with aws_vpc_endpoint_service data source
@jamesbursa showed that the information about an AWS service's region/az availability can be fetched from the data source aws_vpc_endpoint_service rather than hardcoded. This change removes the hardcoding of the region/AZs for the Evidently service and uses this data source instead. An additional benefit is that this approach will make the VPC endpoint resource configuration for other existing and future services more robust.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/78
> Remove workaround for VPC endpoint availability

- infra/app/app-config/env-config/outputs.tf
- infra/app/database/main.tf
- infra/modules/database/variables.tf
n/a
see title
Cleanup : This config value isn't used anywhere.
Developed and tested on platform-test in https://github.com/navapbc/platform-test/pull/79
> Remove unused config value

- infra/test/infra_test.go
n/a
see title
If there's an error in the terraform for the service layer, then the terraform apply fails, which means the cleanup step that sets force_destroy = true for the buckets will also fail since the cleanup also does a terraform apply. This change uses a targeted apply to make the cleanup step more robust. This is similar to the change in this PR — https://github.com/navapbc/template-infra/pull/487 — but for ci-infra-service.yml instead of template-only-ci-infra.yml.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/80
> Make infra service test cleanup more robust

- .github/workflows/ci-infra-service.yml
- infra/modules/feature-flags/logs.tf
- infra/modules/feature-flags/main.tf
Resolves #529 
see title
The default resource policy for log group delivery was getting way too big causing CI to fail
Developed and tested on platform-test in https://github.com/navapbc/platform-test/pull/82
> Create resource policy for feature flags log group

- template-only-test/template_infra_test.go
n/a
see title
Developer experience improvement to have the summary of the template infra tests show more detail about which things passed and which failed, to make it easier to know which set of logs to dive into.
Before:
After:
> Restructure template test output

- bin/set-up-current-account.sh
- infra/modules/auth-github-actions/main.tf
Resolves #531 
see title
see ticket
This change was pulled directly from somewhere else (it was originally a PR authored by @anybodys reviewed by @daphnegold) so it's already been tested there. And it also should be covered by CI.
> Manage OIDC provider outside of terraform

- bin/set-up-current-account.sh
- infra/modules/auth-github-actions/main.tf
Resolves https://github.com/navapbc/template-infra/issues/526
see title
@daphnegold discovered a regression where set-up-account failed when region was not us-east-1
Developed and tested on platform-test in https://github.com/navapbc/platform-test/pull/83
> Fix accounts setup for other regions

- bin/lint-markdown.sh
Resolves 
[lint-markdown.sh](https://github.com/navapbc/template-infra/blob/main/bin/lint-markdown.sh) unnecessarily analyzes `md` files under `node_modules/`.
Exclude files under `*/node_modules/`  from being analyzed by adding the arguments `-not -path "*/node_modules/*"`.
The `gaurav-nelson/github-action-markdown-link-check` action [ignores node_modules files](https://github.com/navapbc/bid-fed-va-spruce-challenge-practice3/actions/runs/7576561682/job/20635654502?pr=4#step:4:109).
- Instantiate the `infra` and `nextjs` templates into a single repo.
- Run `npm install` for the nextjs application so that a `node_modules` subfolder is populated
- Run `bin/lint-markdown.sh` and ensure the `md` files under the `node_modules` subfolder are not analyzed
> Exclude node_modules subfolder for lint-markdown.sh

- bin/lint-markdown.sh
Resolves [lint-markdown.sh](https://github.com/navapbc/template-infra/blob/main/bin/lint-markdown.sh) unnecessarily analyzes `md` files under `.venv/`.
Exclude files under `*/.venv/`  from being analyzed by adding the arguments `-not -path "*/.venv/*"`.
Similar to #543 
- Instantiate the `infra` and `flask` templates into a single repo.
- Set up the flask application so that a `.venv` subfolder is populated
- Run `bin/lint-markdown.sh` and ensure the `md` files under the `.venv` subfolder are not analyzed
> Exclude .venv subfolder for lint-markdown.sh

- .github/workflows/ci-infra-service.yml
- infra/app/service/main.tf
n/a
see title
Was seeing the following error in the ci-infra-service.yml workflow
```
Error refreshing state: unsupported checkable object kind "var"
```
From terraform docs (https://developer.hashicorp.com/terraform/language/upgrade-guides) it looks like upgrading to terraform 1.7.2 resolves this issue.
Developed and tested on platform-test in https://github.com/navapbc/platform-test/pull/86
> Update terraform version

- app/app.py
- docs/infra/environment-variables-and-secrets.md
- infra/README.md
- infra/app/app-config/env-config/environment-variables.tf
- infra/app/app-config/env-config/file_upload_jobs.tf
- infra/app/app-config/env-config/outputs.tf
- infra/app/app-config/env-config/variables.tf
- infra/app/service/main.tf
- infra/modules/service/access-control.tf
- infra/modules/service/main.tf
- infra/modules/service/secrets.tf
- infra/modules/service/variables.tf
Work for https://github.com/navapbc/template-infra/issues/535 and https://github.com/navapbc/template-infra/issues/310
Add functionality for applications to:
* Define application specific environment variables
* Override values for these environment variables per application environment
* Access secrets in SSM parameter store that get injected to the container as environment variables
This adds the ability for applications to define custom env vars and secrets
platform-test-flask needs some manual changes since currently there are custom changes to infra/app/service/main.tf to define the API key
Developed and tested in platform-test in this PR https://github.com/navapbc/platform-test/pull/85
> Configure app env vars and secrets

- docs/infra/module-architecture.md
Fixing an inaccuracy in the diagram. Network layer shouldn't be specific to the app.
Old
New
> Move network layer out of app in arch diagram

- .github/workflows/deploy.yml
N/A
see title
Noticed that a project with multiple apps could not deploy concurrently. Removed this restriction.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/87
> Allow multiple apps to deploy concurrently

- infra/modules/storage/access-control.tf
Resolves https://github.com/navapbc/template-infra/issues/552
see title
The ecs task could put files to S3 but couldn't add tags to those files. This change adds the permissions to add tags. This was discovered while working on another project.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/88
> Add object tagging permissions

- docs/infra/https-support.md
- docs/infra/set-up-custom-domains.md
- docs/infra/set-up-network.md
- infra/app/app-config/dev.tf
- infra/app/app-config/env-config/outputs.tf
- infra/app/app-config/env-config/variables.tf
- infra/app/app-config/prod.tf
- infra/app/app-config/staging.tf
- infra/app/service/main.tf
- infra/modules/domain/certificates.tf
- infra/modules/domain/main.tf
- infra/modules/domain/outputs.tf
- infra/modules/domain/query-logs.tf
- infra/modules/domain/variables.tf
- infra/modules/service/dns.tf
- infra/modules/service/load-balancer.tf
- infra/modules/service/networking.tf
- infra/modules/service/variables.tf
- infra/networks/main.tf
- infra/networks/outputs.tf
- infra/project-config/main.tf
- infra/project-config/networks.tf
Resolves https://github.com/navapbc/template-infra/issues/163
* Add domain config options to the network config objects in project-config module
* Domain config has `hosted_zone`, `manage_dns`, and `certificate_configs` options
* Certificate config has `source` option
* Add domain module which creates Route53 hosted zone and ACM issued SSL certificates
* Add `domain_name` and `enable_https` to environment config objects in app-config module
* Update service module to create A record routing traffic from custom domain to load balancer
* Update service module to attach SSL certificate to load balancer
* Add instructions for setting up custom domains and HTTPS
First review the instructions to see how a project would use this:
1. [Review changes to set up network …
> Add support for custom domains and HTTPS

- .github/workflows/build-and-publish.yml
n/a
see title
When there are multiple apps, the build and publish workflow run name doesn't differentiate between them. This change adds the name and ref (branch or git hash) to the run name to improve developer experience.
Developed and tested in https://github.com/navapbc/platform-test/pull/92
> Add app and ref to build workflow run name

- .github/workflows/README.md
N/A
- Fill in empty `/.github/workflows/README.md`
I don't believe we have any documentation about how our CI/CD workflows are setup, so a new user to the template has to piece together how all the `.github/workflows` fit together. Adding some documentation around it.
N/A
> Explain CI/CD flow and files

- Makefile
A few different tweaks to improve generality and usefulness:
- Break up the core command across a few lines to be more readable
- Add `-h` to the grep to ensure filenames are never printed (say if you
import/include another makefile)
- Add `column` into the mix to ensure things line up given arbitrarily long
target names
- Print some of the variables used in the file's targets as a part of the help
message, to aid debugging and for context
> makefile: Improve help target

- Makefile
When a target has dependencies, put the help text on a different line for
clarity/maintainability.
> makefile: Breakout make target help text from target dependencies

- .github/actions/configure-aws-credentials/action.yml
- bin/configure-monitoring-secret.sh
- bin/publish-release.sh
- bin/run-database-migrations.sh
- bin/set-up-current-account.sh
N/A
- Remove all instances of `terraform <plan|apply> -refresh-only`
A couple days ago, multiple people working with different git repos that use the template-infra started to notice deploy failures showing this error:
```
AWS account authentication details
╷
│ Error: Cannot apply non-applyable plan
│ 
│ The given plan is not applyable. If this seems like a bug in Terraform,
│ then please report it!
╵
Error: Process completed with exit code 1.
```
This is happening during the [Configure AWS Credentials](https://github.com/navapbc/template-infra/blob/main/.github/actions/configure-aws-credentials …
> Remove terraform -refresh-only commands

- infra/modules/service/main.tf
Resolves https://github.com/navapbc/template-infra/issues/600
see title
Unclear when this started happening, it's possible it's related to when we upgraded either terraform or when we upgraded the AWS provider, but in any case the terraform plan in the service layer is always showing a diff now even after applying any changes. This change adds some AWS default parameters to container_definitions.json to cause the plan to show a clean diff.
Developed and tested on platform test in https://github.com/navapbc/platform-test/pull/97
> Add AWS defaults to container definitions to produce clean tf plan

- docs/infra/set-up-app-env.md
- docs/infra/set-up-aws-account.md
- infra/app/app-config/dev.tf
- infra/app/app-config/env-config/outputs.tf
- infra/app/app-config/env-config/variables.tf
- infra/app/app-config/main.tf
- infra/app/app-config/outputs.tf
- infra/app/app-config/prod.tf
- infra/app/app-config/staging.tf
Resolves https://github.com/navapbc/template-infra/issues/458
- Add shared_account_name property to app-config
- Add account_name to env-config
- Refactor account_names_by_environment
- Update docs
For consistency with how we map environments to networks using the environment_config.network_name, this change refactors how we map environments to AWS accounts to use environment_config.account_name. There's a special case for the build-repository which is not part of any application environment but rather shared across all environments. For this we add a new property in app-config called shared_account_name. We can then delete the old account_names_by_environment map, which was a little clunky to explain.
Developed and tested in platform-test in …
> Move account name config into into env-config

- .github/workflows/build-and-publish.yml
- bin/is-image-published.sh
Resolves https://github.com/navapbc/template-infra/issues/610
Resolves https://github.com/navapbc/template-infra/issues/609
- Skip build step if image already published
- Use commit hash of input.ref for build job concurrency
The build-and-publish worklflow always builds the image and only checks if the image is already published when getting ready to publish. This change moves the published image check before the build step, allowing the workflow to skip the build step altogether if the build has already been published.
In addition, this change fixes the build job concurrency to use the commit hash of the commit being built, not the commit hash of the workflow.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/100
> Skip build step if image already published

- docs/infra/set-up-app-build-repository.md
Noticed that the "set up build repository" step doesn't have a step to check that the resource was created properly. Noticed this while working with @allthesignals on his project.
> Add instruction to check build repository

- docs/infra/upgrade-database.md
- infra/modules/database/main.tf
- infra/modules/database/role_manager/manage.py
Resolves #523
- Bump from 14.6 to 16.2
- Add documentation to describe how to do a major version change if desired.
Small tweaks to the code to make upgrading major versions slightly easier:
- Specify `allow_major_version_change = false` -- this is the default, but making it explicit makes it easier for teams to know where this should be updated when they need to change it to true 
- ~Remove revocation of create on public schema from role_manager.py~ -- this is now the default as of Postgres 15, but I'm leaving this behavior "as is" so folks can continue to use the infra template with past versions of Postgres safely.
- Suffix the name of the parameter group with the major engine version. This saves a small manual step when doing a major database change, since otherwise users have to edit …
> Bump to 16.2

- template-only-bin/update-template.sh
n/a
- Add `.gitignore` to update-template.sh, to keep in sync with `install-template.sh`
- https://github.com/navapbc/template-infra/commit/ebec2561a3716c1e3e07255b07ed408040722415 updated install-template.sh
> Include .gitignore in upload-template.sh

- docs/infra/set-up-network.md
n/a
- Small tweak to network documentation to clarify that you only need to take a step if you've made previous (optional) changes during the network set up.
- This confused me when I was trying to set up the template by myself; I then talked to a colleague who mentioned they had the same issue. (n=2)
- This update reflects my own understanding of what could cause this step to be non-optional (either a change to the default environments of dev/stage/prod, or a change to the default network) -- if that's not right or I'm missing something, please let me know!
> Update network docs

- infra/modules/database/role_manager/check.py
- infra/modules/database/role_manager/db.py
N/A
- Update database layer's role manager print strings
In `/infra/modules/database/role_manager`, some of the `print()` calls introduced in #622 aren't formatted correctly. 
This PR:
- Uses python fstrings for all `print()` string interpolation 
- Uses regular strings (i.e. removes the fstring) if the `print()` call isn't doing any string interpolation
> Provide evidence that the code works as expected. Explain what was done for testing and the results of the test plan. Include screenshots, [GIF demos](https://www.cockos.com/licecap/), shell commands or output to help show the changes working …
> Fix role manager print strings

- infra/modules/database/role-manager.tf
N/A
see title
Previously we only ran installation of role manager packages when the requirements.txt file changed, but this means that new infra engineers who ran terraform apply without having the packages installed locally would update the terraform lambda function to a zip file that didn't contain the dependencies, breaking the role manager.
In this PR https://github.com/navapbc/template-infra/pull/452/files we changed the package installation to always install, which fixed the issue but created an annoying situation where the terraform plan would always show changes to apply.
This change introduces a hybrid solution that works around the new engineer issue by triggering an installation of role manager packages locally if the zip archive doesn't exist locally. Otherwise it relies on …
> Refine replace trigger for installation of role manager packages

- infra/test/infra_test.go
N/A
- Updates CI test called in "CI Infra Service Checks"
Now that #649 has been merged, the `infra_test.go` service layer test no longer needs to run a separate `terraform apply` to remove deletion protection on service resources. Since the CI job runs in a terraform workspace, the resources are no longer deployed with deletion protection. 
This PR removes the no longer needed code in the test.
> Provide evidence that the code works as expected. Explain what was done for testing and the results of the test plan. Include screenshots, [GIF demos](https://www.cockos.com/licecap/), shell commands …
> Remove no longer needed manual deletion in CI Infra Service Checks

- .github/workflows/README.md
- .github/workflows/build-and-publish.yml
- .github/workflows/ci-app-pr-environment-destroy.yml
- .github/workflows/ci-app-pr-environment-update.yml
- .github/workflows/pr-environment-destroy.yml
- .github/workflows/pr-environment-update.yml
- README.md
- bin/destroy-pr-environment
- bin/update-pr-environment
- docs/infra/pull-request-environments.md
- infra/app/app-config/main.tf
- template-only-docs/set-up-pr-environments.md
Resolves https://github.com/navapbc/template-infra/issues/139
Add callable reusable github action workflows that:
- creates or updates a temporary environment in a separate workspace
- destroys the temporary environment and workspace
Add template github action workflows for an app that calls the above reusable workflows to:
- create or update a temporary dev environment when a PR is opened, updated, or reopened
- destroys the temporary environment when the PR is closed
Add documentation around PR environments
This is a feature that has proven to be quite useful on a number of projects, enabling product managers and designers to see and collaborate with engineers on in progress features to UAT the feature or otherwise give feedback on it.
This feature will also enable things like …
> Add pull request environments

- .github/actions/configure-aws-credentials/action.yml
- infra/app/app-config/dev.tf
- infra/app/app-config/env-config/outputs.tf
- infra/app/app-config/env-config/variables.tf
- infra/app/app-config/main.tf
- infra/app/app-config/outputs.tf
- infra/app/app-config/prod.tf
- infra/app/app-config/staging.tf
- infra/app/build-repository/main.tf
- infra/project-config/networks.tf
Resolves https://github.com/navapbc/template-infra/issues/670
- Add account_name to network configs
- Remove account_name from environment configs
- Remove account_names_by_environment from app-config
- Add ability for configure-aws-credentials custom action to log in by account_name and network_name
See ticket.
Also, this is a prerequisite for #117 
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/119
> ⚠️ Move account_name from app config to network config

- bin/destroy-pr-environment
n/a
see title
I think the PR environment destroyed comment is also noisy since it sends an email notification and it's never actionable.
Developed and tested in platform-test in https://github.com/navapbc/platform-test/pull/120
> Don't comment on PR after destroying PR environment

- infra/app/app-config/env-config/variables.tf
- infra/modules/domain/variables.tf
- infra/modules/secret/variables.tf
- infra/modules/service/variables.tf
Fixes #618 
- Correct missing spaces, indentation and typos
[platform-test PR](https://github.com/navapbc/platform-test/pull/121)
> Fix EOT formatting

- .github/workflows/check-ci-cd-auth.yml
- .github/workflows/ci-docs.yml
- .github/workflows/ci-infra-service.yml
- .github/workflows/ci-infra.yml
- .github/workflows/database-migrations.yml
- .github/workflows/deploy.yml
- .github/workflows/template-only-cd.yml
- .github/workflows/template-only-ci-app.yml
- .github/workflows/template-only-ci-infra.yml
- .github/workflows/vulnerability-scans.yml
Resolves #662
> replace `actions/checkout@v3` with `actions/checkout@v4` everywhere
[platform-test PR](https://github.com/navapbc/platform-test/pull/122)
> Upgrade actions/checkout to v4

- .github/workflows/pr-environment-destroy.yml
- .github/workflows/pr-environment-update.yml
n/a
see title
Not exactly sure what the exact repro is, but in some situations `gh pr edit` tries to read the organization's github projects, which is a bug in github cli. this change workaround that issue by providing the read access.
Developed and tested on an internal project
see 🔒 [slack thread ](https://nava.slack.com/archives/C069Y4MEUR3/p1722026153896419?thread_ts=1721923216.427679&cid=C069Y4MEUR3)
> Workaround GitHub CLI bug that requires project read permissions

- .github/workflows/check-infra-deploy-status.yml
Resolves https://github.com/navapbc/template-infra/issues/700
see title
See ticket
Tested directly on template-infra this time since template-infra has no root modules to check (which is the scenario we are dealing with) while platform-test does.
Ran the workflow before making any changes to reproduce the fact that it shows as failed: https://github.com/navapbc/template-infra/actions/runs/10100187764
Ran it again after the changes to show that it now shows as successful:
https://github.com/navapbc/template-infra/actions/runs/10100231311
> Skip infra deploy status check if nothing to check

- .github/workflows/template-only-ci-infra.yml
- template-only-test/template_infra_test.go
- template-only.mak
Resolves https://github.com/navapbc/template-infra/issues/686
see title
(see ticket)
tldr: Moving to a fresh new account to make it easier to clean up things when template CI fails since old account has extra stuff in it
Template CI should still work
> Migrate template CI to nava-platform-infra account

- template-only-bin/install-template
- template-only-bin/update-template
Resolves https://github.com/navapbc/template-infra/issues/727
Adds `e2e` to the list of folders to install / update
You can see the issue by looking at the different between these two commits
[template-infra commit](https://github.com/navapbc/template-infra/commit/48c76567034b229c738730972ad35a467aa1e9f8)
[platform-test commit](https://github.com/navapbc/platform-test/commit/8fcbbaecbc664b6f47bd46fb25f2713f1bc93aa9#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52)
The platform test commit is missing the `e2e` folder
I haven't tested this, since the change is small enough that it doesn't seem worthwhile to do a standalone test for it. LMK if you disagree, though.
> Sync the e2e folder when updating the template

- infra/app/service/main.tf
- infra/modules/service/jobs.tf
Resolves #724
- Update app/service root module aws provider version to `>= 5.35.0, < 6.0.0`
This PR updates the `/infra/app/service` root module's aws provider version. It is currently pinned to `>=4.56.0, < 5.0.0`. This PR brings it to `>= 5.35.0, < 6.0.0`.
This supports more recent updates that include data and resource endpoints for AWS Pinpoint and AWS SESv2.
> Provide evidence that the code works as expected. Explain what was done for testing and the results of the test plan. Include screenshots, [GIF demos](https://www.cockos.com/licecap/), shell commands or output to help show the …
> Update app/service root module aws provider version to >=5.35.0

- app/Dockerfile
- app/app.py
- app/templates/index.html
- e2e/package-lock.json
Resolves https://github.com/navapbc/template-infra/issues/733
See title
I already merged the fix in platform-test (see https://github.com/navapbc/platform-test/pull/132) since example app changes don't get pushed from the template, but it'd be nice to make the change here too
See https://github.com/navapbc/platform-test/pull/132
> Fix axe scan in example app

- bin/is-image-published
- bin/publish-release
- infra/app/app-config/build-repository.tf
- infra/app/app-config/main.tf
- infra/app/app-config/outputs.tf
- infra/app/build-repository/main.tf
- infra/app/service/main.tf
- infra/modules/service/access-control.tf
- infra/modules/service/main.tf
- infra/modules/service/variables.tf
- template-only-test/template_infra_test.go
Resolves https://github.com/navapbc/template-infra/issues/716
- Configure prod environment in separate prod AWS account
- Move build repository config to separate file under app-config module
- Consolidate image_repository_name config under build_repostiory_config.name
- Add network_name, account_name, account_id, repository_arn, and repository_url attributes to build repository config
- Replace ecr_repository data source in modules/service with image_repository_arn and image_repository_url passed in through variables
The FFS project discovered a bug in multi-account project setups. The service module determined the build repository ARN and URL using a data source, but a data source can only fetch resources in the same account. In order to address this, we need to eliminate the data …
> Fix access to build repository from different AWS account

- infra/modules/feature-flags/logs.tf
- infra/modules/feature-flags/main.tf
N/A
- Remove manually defined CloudWatch log resource policy for Evidently
We started hitting the Cloudwatch Log resource group policy limit which is causing PR environments to fail to be created (see [example failure](https://github.com/navapbc/pfml-starter-kit-app/actions/runs/10238456987/job/28322961337?pr=198)). You can only have [up to 10 resource policies per region per account, a quota that can't be changed](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html). AWS automatically creates and modifies a resource policy, but that policy has a 5120 character limit. According to AWS docs, [the mitigation is to use log groups that have a prefix of /aws/vendedlogs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html#AWS …
> Remove manually defined CloudWatch log resource policy

- .github/actions/configure-aws-credentials/action.yml
n/a
see title
The configure-aws-credentials action errors if network_name has dashes in it e.g. if network_name = "non-prod"
This issue was discovered on a project.
Tested the change in the other project
> Fix configure-aws-credentials when network_name has dashes

- .github/workflows/build-and-publish.yml
- .github/workflows/cd-app.yml
- .github/workflows/database-migrations.yml
- .github/workflows/deploy.yml
Resolves https://github.com/navapbc/template-infra/issues/693
Pass the value along to the other workflows as necessary.
Update `build-and-publish` to provide an output for the commit actually
built/referenced by the version value, and thread that back through to the
actions for checking/building/deploying the version. Also update it to check for
an existing image by the commit being built and not the git ref passed in (so
multiple builds requested for the same branch/tag name that point at different
commits each time actually build a new image based on the current commit).
See `platform-test` PR: https://github.com/navapbc/platform-test/pull/137
> Add input for which version to deploy on `Deploy App` workflow

- bin/deploy-release
n/a
- If waiting for a stable ECS service fails during deploy, try it exactly one more time
- For two applications using the template-infra, the Nava Labs Decision Support Tool project, and an internal Nava tool, the ECS service takes slightly more than 10 minutes to become stable (typically about 11 or 13).
- The AWS wait command can't be configured to allow more than 10 minutes
- Other approaches considered:
- Sleeping. This is probably the simplest solution but doesn't seem as robust as simply trying the command twice.
- Retrying a configurable number of times in a loop. This seems like premature complexity.
Tested on internal tool (posted in Slack)
> Retry wait for stable service in deploy release

- .github/workflows/template-only-cd.yml
n/a
Update template CD to:
- Keep lorenyu/platform-cli branch up to date with main
- Install nava-platform CLI
- Use nava-platform CLI to update platform-test repos
As part of migrating to use the Platform CLI we are going to first get the platform-test* repos to start updating using the Platform CLI
Temporarily pushed to corresponding lorenyu/platform-cli branches on the platform-test repos:
- https://github.com/navapbc/platform-test-nextjs/compare/main...lorenyu/platform-cli
- https://github.com/navapbc/platform-test-flask/compare/main...lorenyu/platform-cli
Successful run: https://github.com/navapbc/template-infra/actions/runs/11508261320
Screenshot of the resulting diff in one of the platform-test repos
> Update template CD to use Platform CLI

- Makefile
- Fast follow to https://github.com/navapbc/template-infra/issues/735
- Move e2e targets above infra targets
- Give infra targets a comment block header
- Give lint target a comment block header
- We have some nicely namespaced sections so it seemed like we should keep them in order
- Technically the helper scripts are at the bottom so maybe the phony list should reflect that
> Alphabetize makefile

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/check-ci-cd-auth.yml
- .github/workflows/ci-infra-service.yml
- .github/workflows/ci-infra.yml
- .github/workflows/template-only-ci-infra.yml
These are actions that were still using `node16`, which is no longer supported
by GitHub. The updated versions have migrated to `node20`.
Updated:
- aws-actions/configure-aws-credentials v3 -> v4
- actions/setup-python v4 -> v5
- actions/setup-go v3 -> v5
No breaking changes listed in the updates for these actions. Though notably
`setup-go` has enabled caching by default.
See CI, which runs all the updated workflows, except for `.github/workflows/check-ci-cd-auth.yml` I believe.
> Update obsolete GitHub Actions

- .github/workflows/e2e-tests.yml
- e2e/Dockerfile
- e2e/playwright.config.js
Resolves #720 
- Add sharding in CI workflow
- Creates a blob report in each shard, that is merged into an html report that is uploaded to GH Action artifacts  
- Will likely be part 1 of 2 PR to help split up the work a bit - additional items in future PR:
-   [make target for merge report command](https://github.com/navapbc/platform-test-nextjs/pull/89#discussion_r1831428691)
-  [Supporting shard report upload if not all the shards complete successfully](https://github.com/navapbc/platform-test-nextjs/pull/89#discussion_r1831444642)
-  Docker caching/build improvements 
-  Docs updates
- On the `platform-test-nextjs` PR - there was an update to `./e2e/package-lock.json` but I believe that's not needed for final merge here as no package.json packages were updated
- Tested on …
> Run e2e tests in parallel shards

- .github/workflows/e2e-tests.yml
- Makefile
- docs/e2e/e2e-checks.md
Resolves https://github.com/navapbc/template-infra/issues/720
- wrap playwright merge cmd in make target `e2e-merge-reports`
- set matrix `fail-fast` to false so reports can be generated if one of the shards fails
- update docs for sharding
- This PR tested on `platform-test-nextjs` => https://github.com/navapbc/platform-test-nextjs/pull/90 
- See local demos there  
- Sharding part 1 PR https://github.com/navapbc/template-infra/pull/776
Diff comparison with `platform-test-nextjs` PR:
That PR: 
This PR:
> Finish running e2e tests even when one shard fails

- e2e/playwright.config.js
Ticket
Resolves #788 
update base config ./e2e/playwright.config to never open html report
Tested on `platform-test-nextjs` https://github.com/navapbc/platform-test-nextjs/pull/92
- original slack thread https://nava.slack.com/archives/C03G1SWD9H7/p1732305995737349
This PR diff: 
`platform-test-nextjs` PR diff:
> Fix e2e docker hang by never opening html playwright report

- Makefile
- docs/e2e/e2e-checks.md
- e2e/Dockerfile
- e2e/app/playwright.config.js
- e2e/package.json
- e2e/run-e2e-test
Resolves #795 
- Fix E2E ui mode with new npm `e2e-test:ui` command
- Add `e2e-merge-reports` npm run command
- Add `ENTRYPOINT` with optional additinoal `CMD` args in `./e2e/Dockerfile`
- allow `E2E_ARGS` to be passed via make native targets
- Make `BASE_URL` optional in `./e2e/run-e2e-tests`
- Allow command args to be passed to `./e2e/run-e2e-tests`
- Update several `e2e-clean` make targets
- Use variable for e2e image name in Makefile
- Update e2e docs 
- Tested on https://github.com/navapbc/platform-test-nextjs/pull/93
* there were a few additional changes that were added just on this PR
on platform-test-nextjs:
on this PR:
> Streamline e2e commands

- .github/workflows/build-and-publish.yml
- .github/workflows/check-ci-cd-auth.yml
- .github/workflows/check-infra-deploy-status.yml
- .github/workflows/ci-infra-service.yml
- .github/workflows/pr-environment-checks.yml
- .github/workflows/pr-environment-destroy.yml
- .github/workflows/template-only-ci-infra.yml
Resolves #974
- Consistently set up Terraform before later steps that rely on it
- Replace direct references to the Hashicorp action with the custom action that uses .terraform-version
- Latest Ubuntu removed Terraform
- Note that I checked for instances of the AWS credentials workflow only since I know those require Terraform -- I didn't do a wider audit of other workflows that might require it too.
Updated actions running (or at least successfully getting past the AWS credentials step) in platform-test: 
build-and-publish.yml: 🟢 [here](https://github.com/navapbc/platform-test/actions/runs/12432940237/job/34713434814)
check-ci-cd-auth.yml: TBD, need ARN of IAM role to assume
check-infra-deploy-status.yml: 🟢 [here](https://github.com/navapbc/platform-test/actions/runs/12432991469) …
> fix: Setup Terraform in CI/CD workflows

- infra/app/app-config/env-config/main.tf
- infra/app/app-config/env-config/notifications.tf
- infra/app/app-config/main.tf
- infra/app/service/identity_provider.tf
- infra/app/service/main.tf
- infra/app/service/notifications.tf
- infra/modules/identity-provider/resources/main.tf
- infra/modules/identity-provider/resources/variables.tf
- infra/modules/notifications-email-domain/resources/main.tf
Relates to https://github.com/navapbc/template-infra/issues/690
Fixes two bugs that were causing notifications not to work:
- updated the terraform AWS provider version
- swapped `local.dash_domain` and `var.domain_name`
Changes the identity provide module to require SES, and then use SES for email notifications:
Makes notifications rely on two variables being defined for a given environment: `hosted_zone` and `domain_name`
Moves the Congito IDP config out of `infra/app/service/main.tf` and into its own file
Despite the smallish diff, this took dang forever
Tested with notifications both on and off via https://github.com/navapbc/pfml-starter-kit-app/pull/237
> Make Cognito use SES for notifications

- .github/workflows/check-infra-deploy-status.yml
Resolves https://github.com/navapbc/template-infra/issues/806
see title
Leveraging the previously added workflow to send notifications for failed infra status check workflow
developed and tested on platform test see https://github.com/navapbc/platform-test/pull/149
> Send notification for failed infra deploy status check

- .github/workflows/ci-app-pr-environment-destroy.yml
Fixes bug where PR environment destroy workflow is not triggered when there is a conflict with the base branch
Resolves https://github.com/navapbc/template-infra/issues/826
see title
see ticket. i looked into why PRs were being orphaned and discovered it's not because PR destroy workflow was failing but because it wasn't being triggered at all.
developed in platform test https://github.com/navapbc/platform-test/pull/151 but realized it's hard to test since the change won't be on the base branch since it's not merged yet. So gonna bypass testing and merge this for now.
> Fix trigger for PR environment destroy workflow

- .github/workflows/scan-orphaned-pr-environments.yml
n/a
see title
Noticed this problem on a private repo. Didn't notice this problem before because platform-test is a public repo so it didn't need explicit permissions to access the pull requests of the public repo.
developed and tested in the private repo
> Fix permissions for scan orphaned PRs workflow

- bin/update-pr-environment
- infra/{{app_name}}/app-config/env-config/main.tf
- infra/{{app_name}}/app-config/env-config/outputs.tf
- infra/{{app_name}}/service/main.tf
- infra/{{app_name}}/service/storage.tf
Resolves https://github.com/navapbc/template-infra/issues/654
- Move prefix local var from env-config module to service layer's root module
- Move storage resources to separate storage.tf file
See ticket
see https://github.com/navapbc/platform-test/pull/153
> Move prefix from env-config to service root

- infra/modules/notifications-email-domain/resources/dns.tf
- infra/modules/notifications-email-domain/resources/variables.tf
- infra/{{app_name}}/service/identity_provider.tf
- infra/{{app_name}}/service/main.tf
- infra/{{app_name}}/service/notifications.tf
N/A
- Use service_config.domain_name for notifications-email-domain module
- DRY up usage of domain_name and hosted_zone_id in service root module by defining local variables
We originally thought that the domain for the SES domain identity we create had to be the same as the root of the hosted zone domain rather than a subdomain, but we were wrong. This change causes the domain identity to just reuse the same domain as the app's configured domain, which simplifies things and also removes the chance of conflict between two apps that enable notifications.
see 🔒 https://github.com/navapbc/pfml-starter-kit-app/pull/245
> Reuse app domain for domain identity

- infra/modules/network/variables.tf
- infra/modules/network/vpc_endpoints.tf
- infra/modules/notifications/resources/access_control.tf
- infra/modules/notifications/resources/outputs.tf
- infra/networks/main.tf.jinja
- infra/{{app_name}}/service/main.tf
- template-only-app/app.py
- template-only-app/notifications.py
- template-only-app/templates/index.html
Contributes to https://github.com/navapbc/template-infra/issues/792
Fix ability for ECS service to access Pinpoint:
- Add VPC endpoints for Pinpoint services
- Add IAM policy for accessing Pinpoint and SES to service
Also add notifications test endpoint to example app for testing:
- Add /notifications page where you can enter an email address and get a test notification to that email address
- Add links to the homepage to all the test pages in the example app
I added /notifications endpoint since it will be useful to test changes to notifications infrastructure, but while testing I discovered some access bugs
see https://github.com/navapbc/platform-test/pull/154
> Fix notifications access from service

- infra/{{app_name}}/service/database.tf
- infra/{{app_name}}/service/domain.tf
- infra/{{app_name}}/service/identity_provider.tf
- infra/{{app_name}}/service/main.tf
- infra/{{app_name}}/service/monitoring.tf
- infra/{{app_name}}/service/network.tf
- infra/{{app_name}}/service/notifications.tf
Resolves https://github.com/navapbc/template-infra/issues/645
- Move incident management resources into monitoring.tf
- Move database related resources into database.tf
- Move VPC related resources into network.tf
- Move custom domain related resources into domain.tf
- Move identity_provider_config variable to identity_provider.tf
- Move notifications_config variable to notifications.tf
The main.tf file for the service layer root module (/infra/{{app_name}}/service) was getting unwieldy, making it hard to read, hard to find specific resources, and also increases the chance of conflicts for projects that need to add customizations to the service layer. This change splits main.tf into separate files based on logical groupings.
see https://github.com/navapbc/platform-test/pull/155
> Organize service root module main.tf into separate files

- infra/modules/identity-provider/resources/main.tf
- infra/modules/identity-provider/resources/variables.tf
- infra/{{app_name}}/app-config/env-config/domain.tf
- infra/{{app_name}}/app-config/env-config/outputs.tf
- infra/{{app_name}}/service/domain.tf
- infra/{{app_name}}/service/identity_provider.tf
- infra/{{app_name}}/service/main.tf
- infra/{{app_name}}/service/notifications.tf
n/a
- Consolidate hosted_zone, domain_name, and enable_https to a domain_config object separate from the service_config object
- Remove unnecessary domain_name variable from identity-provider/resources
While working on another PR I realized the domain configs are intermingled with service configs. This PR cleans that up. There should be no functional changes in this PR, just reorganizing things.
see https://github.com/navapbc/platform-test/pull/157
> Consolidate domain configs

- bin/run-database-migrations
- infra/modules/database/data/outputs.tf
- infra/{{app_name}}/service/outputs.tf
Resolves https://github.com/navapbc/template-infra/issues/845
see title
see ticket, after removing migrator username from app-config the run db migrations script now thinks migrator username is null
see https://github.com/navapbc/platform-test/pull/160
> Fix db migrations

- .github/workflows/build-and-publish.yml
- .github/workflows/ci-{{app_name}}-infra-service.yml.jinja
- infra/test/infra_test.go
Resolves https://github.com/navapbc/template-infra/issues/836
The `ci-{{app_name}}-infra-service.yml` and `cd-{{app_name}}.yml` workflows
occasionally run into issues trying to publish an already existing image tag[1],
failing with something like:
> tag invalid: The image tag '48995925face06c5fcb68fc52c50e7d57bb46ff6' already exists in the 'platform-nextjs-app' repository and cannot be overwritten because the repository is immutable.
I believe what's happening is that for merges to `main`, the two workflows get
kicked off at the same time, both needing build and publish an image for the
same commit and using different methods for doing that building/publishing.
`ci-{{app_name}}-infra-service.yml` runs the commands internally to its test
logic, `cd-{{app_name}}.yml` uses the …
> Fix race condition when publishing images

- docs/e2e/e2e-checks.md
- docs/infra/set-up-app-build-repository.md
- docs/infra/set-up-app-env.md
- docs/infra/set-up-custom-domains.md
- docs/infra/set-up-database.md
- infra/modules/notifications-email-domain/resources/logs.tf
- infra/modules/service/access_control.tf
- infra/modules/service/application_logs.tf
- template-only-docs/set-up-team-workflow.md
- template-only-docs/template-development-workflow.md
- More `app` -> `<APP_NAME>` placeholder updates
- Fix the casing of some proper nouns
- Clarify you don't set the AWS account name in the application environment
configuration anymore, but in the network[1]
- Misc. spelling mistakes/typos
[1] https://github.com/navapbc/template-infra/releases/tag/v0.11.0
Look at it.
> docs: Miscellaneous minor updates

- bin/lint-markdown
Rather than maintaining effectively another ignore list, use the one we already have via git. This also adapts better to usage in child projects, as they will likely have more language/project specific locations to ignore that we can't realistically maintain in this parent template.
Running normally:
```
❯ make lint-markdown                               
./bin/lint-markdown
ERROR: 1 dead links found in docs/decisions/infra/0011-network-layer-design.md !
[✖] #application-specific-network-configuration → Status: 404
ERROR: 1 dead links found in docs/infra/environment-variables-and-secrets.md !
[✖] #secrets → Status: 404
ERROR: 10 dead links found in docs/infra/style-guide.md !
[✖] #style-guide → Status: 404
[✖] #table-of-contents → Status: 404
[✖] #terraform-code-style → Status: 404
[✖] …
```
> bin/lint-markdown: Only run against git-tracked markdown files

- bin/update-pr-environment
- infra/{{app_name}}/service/outputs.tf
The prefix was recently moved from the env-config to the service root[1], with
the effect that the `service_config.service_name` value no longer carries the
running/real service name. Special support was added to the
`bin/update-pr-environment` script to reconstruct the actual service name, but
other things also need the prefixed service name, like `bin/deploy-release` and
`bin/run-command`, and in general feels like we should output the actual service
name.
[1] ab1fda44f30077bc1084a5cabd50d9d465e21699
> Provide evidence that the code works as expected. Explain what was done for testing and the results of the test plan. Include screenshots, …
> Include prefix in service root `service_name` output

- infra/modules/service/main.tf
- infra/modules/service/variables.tf
- infra/{{app_name}}/app-config/env-config/outputs.tf
- infra/{{app_name}}/service/main.tf
Half of solving https://github.com/navapbc/template-application-rails/issues/58
Fargate tasks come with 20 GiB of ephemeral storage[1] by default (the container image size itself eats into this) and can be increased up to a maximum of 200 GiB.
While generally encouraged to store files/write data to a network location/a database, there are situations where it is useful to have some "local" file space to write data to (e.g., tmpfiles, processing a large data file).
Fargate can be configured to mount its allocated ephemeral space into the container to facilitate this. This has a few pieces[2], in summary:
1. Create the desired writable locations in the container image, with the
appropriate permissions/owner, and declare them with a `VOLUME` instruction:
```dockerfile
VOLUME /var/scratch
``` …
> Support ephemeral write mounts for services

- bin/run-command
Resolves https://github.com/navapbc/template-infra/issues/718
Resolves https://github.com/navapbc/template-infra/issues/878
- Add optional parameter --workspace <workspace_name> to bin/run-command
- Fix bug where run-command ignored environment parameter and just ran in currently initialized environment
This feature makes it possible to test changes to background jobs in a PR environment by using the run-command script
See https://github.com/navapbc/platform-test/pull/181
> Add ability to run task commands in PR environment

- docs/infra/set-up-monitoring-alerts.md
- infra/modules/monitoring/main.tf
- infra/modules/monitoring/variables.tf
- infra/{{app_name}}/app-config/env-config/monitoring.tf
- infra/{{app_name}}/app-config/env-config/outputs.tf
- infra/{{app_name}}/service/monitoring.tf
Resolves https://github.com/navapbc/template-infra/issues/547
- Create new env-config object monitoring_config defined in monitoring.tf
- Move incident_management_service_integration config to monitoring_config as incident_management_service attribute
- Rename email_alerts_subscription_list to email_alert_recipients
Tech debt to clean up the configuration for monitoring
See https://github.com/navapbc/platform-test/pull/183
> Move monitoring config out of service root module

- infra/test/infra_test.go
Work towards https://github.com/navapbc/template-infra/issues/787
see title
This is the first step towards https://github.com/navapbc/template-infra/issues/787
The ultimate goal is to have a way to look for stale environments generated by the infra service tests. The way we plan on doing that is to encode timestamp information in the id itself, but because we want the id to be short we are base62 encoding the id.
see https://github.com/navapbc/platform-test/pull/182
> Generate infra service test id from timestamp

- e2e/lib/services/email/EmailService.ts
- e2e/lib/services/email/MailinatorService.ts
- e2e/lib/services/email/MessageCheckerService.ts
- e2e/lib/util.js
- e2e/{{app_name}}/playwright.config.js.jinja
n/a
- Create e2e/lib
- Move e2e/util to e2e/lib
- Add email services
Create e2e/lib, add email services from pfml-starter-kit-app and move util to this folder too
see https://github.com/navapbc/pfml-starter-kit-app/pull/264
> Move test library files to lib

- e2e/fixtures/email-service-fixture.ts
- e2e/fixtures/index.ts
- e2e/{{app_name}}/playwright.config.js.jinja
n/a
see title
Individual tests should not need to know which email service is being used. That should be defined at the e2e test suite configuration level. This change adds an emailService fixture using Playwright fixtures with the default using MessageChecker.
see https://github.com/navapbc/pfml-starter-kit-app/pull/267
> Move emailService to fixture for e2e tests

- bin/orphaned-pr-environments
When there are no PR environments for an application, `grep 'pr-'` against the
workspace names will not match anything, in which case grep returns a code of
`1`. Since `-o pipefail` is set, `grep` returning `1` will fail the pipeline,
and since `-e` is set, the pipeline will fail the script. So catch a return of
`1` from `grep` and continue on.
Also handle merged PR statuses in addition to closed, as that will sometimes be
the case.
Also set a default for `GITHUB_STEP_SUMMARY` for when running the script
locally. 
Errors out when there are no PR envs.
Does not error out.
Doesn't flag dangling PR environment from a merged PR.
> bin/orphaned-pr-environments: Handle no PR envs and merged PRs better

- infra/modules/service/outputs.tf
n/a
- Set public_endpoint to use https protocol when https is enabled
Discovered this while working on e2e testing. Preview environments use the service module public_endpoint output to define the preview environment URL. When HTTPS is enabled we will eventually redirect from HTTP to HTTPS. For Rails apps we already do this at the app level. This means that the preview environment thinks it's at the HTTP endpoint but the server quickly redirects to HTTPS. This breaks end-to-end tests since the tests needs a consistent base URL.
See https://github.com/navapbc/pfml-starter-kit-app/pull/269
It was failing before, and I was able to reproduce the issue and narrow it down to the http vs https cause. After the fix, the e2e tests pass on that PR.
> Fix service module public_endpoint output when https enabled

- Makefile
- docs/e2e/e2e-checks.md
- e2e/Dockerfile
- e2e/package-lock.json
- e2e/package.json
- e2e/playwright.config.js
- e2e/run-e2e-test
n/a
- Remove unused dotenv package
- Remove redundant package playwright (already have playwright/test)
- Remove dotenv package
- Consolidate dependencies and devDependencies
- Testing out whether we need `npm run e2e-setup` to do `npx install playwright` or whether we can just do `npm ci` like any other package 
- I didn't see any .env file so I didn't see the point of the dotenv package either, seems like we can simplify
See https://github.com/navapbc/pfml-starter-kit-app/pull/272
> Simplify e2e setup

- bin/run-command
N/A - No Ticket
* Fix ThrottlingError when running migrations
We've been getting a ThrottlingError when running migrations a few times
(see [1], [2], [3]).
It's because the `--query` argument is evaluated client-side after
receiving the full list from the server, and therefore the
`describe-log-streams` call is paginating through all 174 pages of our
8300+ log streams just to select the single one we're looking for.
Github Actions' internet connection seems to be fast enough to hit the
[25 requests/second rate limit][4].
Let's use the `--log-stream-name-prefix` option instead to filter it
server-side. We can still use a (simpler) `--query` to count the
results client-side.
[1]: https://github.com/DSACMS/iv-cbv-payroll/actions/runs/13775537056/job/38524000928
[2]: …
> Fix ThrottlingError when running migrations

- .github/workflows/build-and-publish.yml
- .github/workflows/cd-{{app_name}}.yml.jinja
- .github/workflows/check-ci-cd-auth.yml
- .github/workflows/check-infra-deploy-status.yml
- .github/workflows/ci-docs.yml
- .github/workflows/ci-infra.yml
- .github/workflows/database-migrations.yml
- .github/workflows/deploy.yml
- .github/workflows/scan-orphaned-pr-environments.yml
- .github/workflows/template-only-cd.yml
- .github/workflows/template-only-ci-infra.yml
- docs/infra/style-guide.md
N/A
- Add style guide for GitHub Actions workflows
- Update workflows to follow style guide
I couldn't find a good style guide on the internet so decided to write my own.
Didn't really do testing, (I'm assuming the changes I'm making are safe)
To demonstrate the change regarding replacing calling workflow job names with whitespace:
Before, long job names, lots of redundancy, and extra prefixes that reveal more about the implementation details rather than being useful e.g. "Deploy / Database Migrations / Build / Build and Publish", "Deploy / Deploy":
After, some awkwardness with "/ / " prefixes but otherwise much cleaner job names:
Also, for checks in pull requests, without replacing job names with "" the job names would be so long that you can't actually see the job being run, you can …
> Add style guide for GitHub Actions

- .github/workflows/deploy.yml
- .github/workflows/e2e-tests.yml
- infra/modules/service/dns.tf
- infra/modules/service/outputs.tf
Resolves https://github.com/navapbc/template-infra/issues/729
- Run e2e tests at end of deploy.yml
- Update modules/service service_endpoint output to use custom domain if set
- Tweak job names to improve readability of job workflows
- Rename job names to " " when calling callable workflows
- Shorten job names to be within 3 words
- Prefix individual shard's blob report artifact names with e2e-test
Run e2e tests at the end of every deploy
see https://github.com/navapbc/platform-test/pull/187
> Run e2e tests at end of deployment

- .github/workflows/scan-orphaned-environments.yml
- bin/stale-test-environments
- bin/util.sh
Resolves https://github.com/navapbc/template-infra/issues/787
- Add bin/stale-test-environments script
- Modify scan-orphaned-pr-environments workflow to scan for stale test environments too and rename the workflow
Builds on the work in https://github.com/navapbc/template-infra/pull/885 to determine if a test environment is stale
See https://github.com/navapbc/platform-test/pull/190
> Check for stale infra service test environments

- .github/workflows/ci-e2e-static-checks.yml
- Makefile
- e2e/package-lock.json
- e2e/package.json
- e2e/tsconfig.json
- e2e/{{app_name}}/tests/index.spec.ts
Resolves #813 
- Add config to run typescript from Makefile
- Add checks on PR / CI
- Update `index.spec.ts` to pass type check
Original PR:
https://github.com/navapbc/pfml-starter-kit-app/pull/276
Diff on `pfml-starter-kit-app` PR: 
Diff on this PR:
* After editing `e2e/{{app_name}}/tests/index.spec.ts`  - the line diffs obviously won't line up
- also added the type check make targets to the makefile `.PHONY` list
> Add e2e typescript

- Makefile
- Fix path for building role manager archive to include /resources subdirectory
- Remove role manager archive before building (since zip just adds to the archive so nothing ever gets removed)
- CD into the role_manager directory and run zip * to avoid recreating full infra/modules/database path in zip archive
Noticed this while working on resetting the schema for app-rails in platform-test repo
Before:
After:
> Fix role manager archive Make target

- .github/workflows/cd-{{app_name}}.yml.jinja
- .github/workflows/deploy.yml
Resolves #{TICKET NUMBER OR URL}
see title
Seems useful to send a slack notification when a deploy fails rather than relying on the email which only goes to the engineer that merged a PR
See https://github.com/navapbc/platform-test/pull/195
> Add deploy failure system notification

- infra/modules/service/load_balancer.tf
Resolves #880 
- Added HTTP to HTTPS redirect rule with priority 50 (lower than the forward rule) when certificate_arn is not null
Paired with Devin AI to implement this
see https://github.com/navapbc/platform-test/pull/198
> Redirect HTTP traffic to HTTPS

- infra/modules/network/data/main.tf
- infra/modules/network/data/outputs.tf
- infra/modules/network/interface/outputs.tf
- infra/modules/network/resources/waf.tf
- infra/modules/service/variables.tf
- infra/modules/service/waf.tf
- infra/{{app_name}}/app-config/main.tf
- infra/{{app_name}}/app-config/outputs.tf
- infra/{{app_name}}/service/main.tf
Resolves #165 #462 
This PR adds Web Application Firewall (WAF) protection to the service layer by:
1. Adding a WAF resource to the network module
2. Adding WAF data source to the network data module
3. Adding WAF input to service module
4. Adding enable_waf config option to app-config (default: true)
5. Updating service root module to attach WAF if enabled
The WAF uses the AWS Managed Common Rule Set for baseline protection.
This PR adds an `enable_waf` configuration to the `app-config` module which defaults to `true`. However, the WAF needs to first be created at the network layer before applying any changes at the service layer, otherwise the service layer will not be able to find the WAF to apply. To do this, apply the network changes by running
```bash
make infra-update-network …
```
> ⚠️ Add WAF protection to application load balancers

- infra/modules/network/resources/waf.tf
n/a
see title
This change helps resolve an issue that can happen when using the AWS managed resource policy
```
module.network.aws_wafv2_web_acl_logging_configuration.main: Creating...
╷
│ Error: putting WAFv2 WebACL Logging Configuration (arn:aws:wafv2:us-east-1:775316947779:regional/webacl/dev/6b2d3994-2183-49c7-85ab-528dddf3d102): WAFLogDestinationPermissionIssueException: Unable to deliver logs to the configured destination. You might need to grant log delivery permissions for the destination. If you're using S3 as your log destination, you might have exceeded your bucket limit.
│ 
│   with module.network.aws_wafv2_web_acl_logging_configuration.main,
│   on ../modules/network/resources/waf.tf line 71, in resource "aws_wafv2_web_acl_logging_configuration" "main":
│   71: resource …
```
> Manually manage WAF Logs resource policy

- docs/infra/web-application-firewall.md
- infra/{{app_name}}/app-config/main.tf
N/A
- Set enable_waf to false in app-config/main.tf
- Update instructions to say that WAF is disabled by default
Since WAF can interfere with E2E testing, leave WAF disabled by default for now, and provide instructions for how to enable it. This also makes it more backwards compatible and allows us to have time to gather feedback from projects using it.
I didn't test this change
> Disable WAF by default

- .github/workflows/ci-e2e-static-checks.yml
- e2e/{{app_name}}/tests/index.spec.ts
Resolves https://github.com/navapbc/template-infra/issues/813
- separate e2e format and typecheck jobs in github actions with matrix strategy
- add `fail-fast:false` to allow all e2e static checks to run regardless of one failure
- add `workflow_dispatch` to manually trigger static checks [to be tested post merge]
The e2e format and typecheck calls were in the same GHA job - this PR just separates them to separate jobs so they can run in parallel.
> Separate e2e format and typecheck jobs

- infra/modules/database/resources/main.tf
Resolves terraform diffs
see title
AWS auto upgraded postgres in RDS aurora from 16.2 to 16.6
This change upgrades Postgres from 16.2 to 16.6. If you do not want to upgrade at this time, revert engine_version back to the original value.
Made this change on platform-test locally and showed no terraform diff
> ⚠️ Update postgres engine version to match what AWS upgraded to

- infra/modules/database/resources/role_manager.tf
Here's the docs for this attribute https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html
Copy pasting them in here in case the link dies
> Reserved concurrency – This represents the maximum number of concurrent instances allocated to your function. When a function has reserved concurrency, no other function can use that concurrency. Reserved concurrency is useful for ensuring that your most critical functions always have enough concurrency to handle incoming requests. Configuring reserved concurrency for a function incurs no additional charges
Reserved concurrency is like a reservation at a restaurant, where the restaurant also has free-floating seating. The reservation is for you, but you can also sit elsewhere. It doesn't relate to maximum concurrent executions.
> Remove inaccurate comment

- .github/workflows/pr-environment-checks.yml
- .github/workflows/pr-environment-destroy.yml
Resolves https://github.com/navapbc/template-infra/issues/937
see title 
I noticed that occasionally the PR environment gets destroyed (successfully) before it gets created again. Looking into it, it looks like if the PR is closed or merged before the PR environment check's build-and-publish job is completed, the PR environment destroy job will actually run first. This change fixes that issue by moving the concurrency key to operate at the workflow level rather than just at on the job level.
Tested on https://github.com/navapbc/platform-test/pull/208
> Fix PR environment destroy race condition

- bin/current-region
A recent change in the AWS CLI[1] updates the output formatting of `aws
configure list`, which breaks the `bin/current-region` script.
In pre-2.31.0 versions the output is:
```
Name                    Value             Type    Location
----                    -----             ----    --------
profile                <not set>             None    None
access_key     ****************ABCD      config_file    ~/.aws/config
secret_key     ****************ABCD      config_file    ~/.aws/config
region                us-west-2              env    AWS_DEFAULT_REGION
```
In 2.31.0+ versions the output is:
```
NAME       : VALUE                    : TYPE             : LOCATION
profile    : <not set>                : None             : None
access_key : ****************ABCD     : config_file      : …
```
> Handle new output format from AWS CLI in `bin/current-region`
